// AUTO-GENERATED 2026-06-11 from the torginol.com product catalog (828 product pages).
// Images live in src/images/flakes/ (legacy) and src/images/torginol/<collection>/ (gitignored, exist locally).
// To refresh: re-run the sitemap crawl + download described in docs/superpowers/specs/2026-06-11-visual-redesign-design.md.
const COLLECTIONS = [
  { key: "signature", title: "Signature Collection", blurb: "Torginol's flagship blends \u2014 the most popular looks in epoxy flooring.", items: [
    {"name": "Cabin Fever", "sku": "FB-127", "file": "flakes/cabin-fever.jpg"},
    {"name": "Creekbed", "sku": "FB-716", "file": "flakes/creekbed.jpg"},
    {"name": "Domino", "sku": "FB-411", "file": "flakes/domino.jpg"},
    {"name": "Gracious", "sku": "FB-916", "file": "flakes/gracious.jpg"},
    {"name": "Gravel", "sku": "FB-414", "file": "flakes/gravel.jpg"},
    {"name": "Nightfall", "sku": "FB-715", "file": "flakes/nightfall.jpg"},
    {"name": "Orbit", "sku": "FB-310", "file": "flakes/orbit.jpg"},
    {"name": "Outback", "sku": "FB-517", "file": "flakes/outback.jpg"},
    {"name": "Shoreline", "sku": "FB-421", "file": "flakes/shoreline.jpg"},
    {"name": "Tidal Wave", "sku": "FB-807", "file": "flakes/tidal-wave.jpg"},
    {"name": "Wombat", "sku": "FB-616", "file": "flakes/wombat.jpg"},
  ] },
  { key: "garage", title: "Garage Collection", blurb: "Purpose-built blends that hide dust, dirt, and tire marks in working garages.", items: [
    {"name": "Bean", "sku": "FB-960", "file": "torginol/garage/bean.jpg"},
    {"name": "Comet", "sku": "FB-711", "file": "flakes/comet.jpg"},
    {"name": "Crossbow", "sku": "FB-320", "file": "flakes/crossbow.jpg"},
    {"name": "Hog", "sku": "FB-606", "file": "torginol/garage/hog.jpg"},
    {"name": "Platteville", "sku": "FB-314", "file": "torginol/garage/platteville.jpg"},
    {"name": "Quicksilver", "sku": "FB-424", "file": "flakes/quicksilver.jpg"},
    {"name": "Stonehenge", "sku": "FB-427", "file": "flakes/stonehenge.jpg"},
    {"name": "Stonewash", "sku": "FB-708", "file": "flakes/stonewash.jpg"},
    {"name": "Yellow Jacket", "sku": "FB-332", "file": "torginol/garage/yellow-jacket.jpg"},
  ] },
  { key: "contemporary", title: "Contemporary Collection", blurb: "Clean, modern palettes for living spaces and showrooms.", items: [
    {"name": "Antler", "sku": "FB-601", "file": "torginol/contemporary/antler.jpg"},
    {"name": "Chenille", "sku": "FB-981", "file": "flakes/chenille.jpg"},
    {"name": "Citrine", "sku": "FB-978", "file": "flakes/citrine.jpg"},
    {"name": "Coyote", "sku": "FB-513", "file": "flakes/coyote.jpg"},
    {"name": "Dingo", "sku": "FB-980", "file": "flakes/dingo.jpg"},
    {"name": "Dovetail", "sku": "FB-823", "file": "flakes/dovetail.jpg"},
    {"name": "Heron", "sku": "FB-976", "file": "flakes/heron.jpg"},
    {"name": "Keystone", "sku": "FB-713", "file": "flakes/keystone.jpg"},
    {"name": "Koala", "sku": "FB-811", "file": "flakes/koala.jpg"},
    {"name": "Madras", "sku": "FB-706", "file": "flakes/madras.jpg"},
    {"name": "Morel", "sku": "FB-979", "file": "flakes/morel.jpg"},
    {"name": "Nordic Green", "sku": "FB-514", "file": "flakes/nordic-green.jpg"},
    {"name": "Polar", "sku": "FB-330", "file": "flakes/polar.jpg"},
    {"name": "Reed", "sku": "FB-507", "file": "flakes/reed.jpg"},
    {"name": "Rocky Ridge", "sku": "FB-801", "file": "flakes/rocky-ridge.jpg"},
    {"name": "Stony Creek", "sku": "FB-806", "file": "flakes/stony-creek.jpg"},
    {"name": "Thyme", "sku": "FB-977", "file": "flakes/thyme.jpg"},
  ] },
  { key: "marble", title: "Marble Collection", blurb: "Soft, stone-inspired tones with a natural marbled read.", items: [
    {"name": "Arkose", "sku": "F9318", "file": "flakes/arkose.jpg"},
    {"name": "Basalt", "sku": "F9309", "file": "flakes/basalt.jpg"},
    {"name": "Blizzard", "sku": "FB-6001", "file": "flakes/blizzard.jpg"},
    {"name": "Carbon", "sku": "F9202", "file": "flakes/carbon.jpg"},
    {"name": "Dolerite", "sku": "F9311", "file": "flakes/dolerite.jpg"},
    {"name": "Feldspar", "sku": "F9203", "file": "flakes/feldspar.jpg"},
    {"name": "Garnet", "sku": "F9305", "file": "flakes/garnet.jpg"},
    {"name": "Lanai Gray", "sku": "F3080", "file": "torginol/marble/lanai-gray.jpg"},
    {"name": "Metapelite", "sku": "F9317", "file": "flakes/metapelite.jpg"},
    {"name": "Obsidian", "sku": "F9304", "file": "flakes/obsidian.jpg"},
    {"name": "Pumice", "sku": "F9303", "file": "flakes/pumice.jpg"},
    {"name": "Sable", "sku": "F9205", "file": "flakes/sable.jpg"},
    {"name": "Schist", "sku": "F9307", "file": "flakes/schist.jpg"},
    {"name": "Soapstone", "sku": "F9320", "file": "flakes/soapstone.jpg"},
    {"name": "Spilite", "sku": "F9313", "file": "flakes/spilite.jpg"},
    {"name": "Sycamore", "sku": "FB-6002", "file": "flakes/sycamore.jpg"},
    {"name": "Talus", "sku": "F9319", "file": "flakes/talus.jpg"},
    {"name": "Weathered Gray", "sku": "FB-6003", "file": "flakes/weathered-gray.jpg"},
  ] },
  { key: "brownstone", title: "Brownstone Collection", blurb: "Warm earth tones \u2014 tans, browns, and desert neutrals.", items: [
    {"name": "Bambi", "sku": "FB-959", "file": "flakes/bambi.jpg"},
    {"name": "Buffalo", "sku": "FB-954", "file": "flakes/buffalo.jpg"},
    {"name": "Chickadee", "sku": "FB-967", "file": "flakes/chickadee.jpg"},
    {"name": "Coldwater Canyon", "sku": "FB-304", "file": "torginol/brownstone/coldwater-canyon.jpg"},
    {"name": "Loon", "sku": "FB-966", "file": "flakes/loon.jpg"},
    {"name": "Merino", "sku": "FB-971", "file": "flakes/merino.jpg"},
    {"name": "Mushroom", "sku": "FB-714", "file": "flakes/mushroom.jpg"},
    {"name": "Quail", "sku": "FB-974", "file": "flakes/quail.jpg"},
    {"name": "Robin", "sku": "FB-973", "file": "flakes/robin.jpg"},
    {"name": "Rosy-Finch", "sku": "FB-969", "file": "flakes/rosy-finch.jpg"},
    {"name": "Safari", "sku": "FB-504", "file": "flakes/safari.jpg"},
    {"name": "Sparrow", "sku": "FB-972", "file": "flakes/sparrow.jpg"},
    {"name": "Swan", "sku": "FB-612", "file": "flakes/swan.jpg"},
    {"name": "Trailmix", "sku": "FB-613", "file": "torginol/brownstone/trailmix.jpg"},
    {"name": "Waxwing", "sku": "FB-968", "file": "flakes/waxwing.jpg"},
    {"name": "Woodland", "sku": "FB-516", "file": "flakes/woodland.jpg"},
    {"name": "Woodpecker", "sku": "FB-975", "file": "flakes/woodpecker.jpg"},
    {"name": "Wren", "sku": "FB-970", "file": "flakes/wren.jpg"},
  ] },
  { key: "greystone", title: "Greystone Collection", blurb: "Cool greys from light fog to deep charcoal.", items: [
    {"name": "Feather Gray", "sku": "FB-905", "file": "flakes/feather-gray.jpg"},
    {"name": "Fog", "sku": "FB-703", "file": "flakes/fog.jpg"},
    {"name": "Galaxy", "sku": "FB-907", "file": "flakes/galaxy.jpg"},
    {"name": "Houndstooth", "sku": "FB-910", "file": "flakes/houndstooth.jpg"},
    {"name": "Moon Mist", "sku": "FB-906", "file": "flakes/moon-mist.jpg"},
    {"name": "Opal", "sku": "FB-901", "file": "flakes/opal.jpg"},
    {"name": "Raven", "sku": "FB-915", "file": "flakes/raven.jpg"},
    {"name": "Shadow", "sku": "FB-913", "file": "flakes/shadow.jpg"},
    {"name": "Silver Bells", "sku": "FB-903", "file": "flakes/silver-bells.jpg"},
    {"name": "Snowfall", "sku": "FB-602", "file": "flakes/snowfall.jpg"},
    {"name": "Stargazer", "sku": "FB-908", "file": "flakes/stargazer.jpg"},
    {"name": "Thunder", "sku": "FB-912", "file": "flakes/thunder.jpg"},
    {"name": "Timberwolf", "sku": "FB-909", "file": "flakes/timberwolf.jpg"},
    {"name": "Wild Dove", "sku": "FB-911", "file": "flakes/wild-dove.jpg"},
  ] },
  { key: "terrazzo", title: "Terrazzo Collection", blurb: "Bold terrazzo-style chips for a classic composite look.", items: [
    {"name": "Acadia", "sku": "FB-4208", "file": "torginol/terrazzo/acadia.jpg"},
    {"name": "Alameda", "sku": "FB-4202", "file": "torginol/terrazzo/alameda.jpg"},
    {"name": "Anchorage", "sku": "FB-4204", "file": "torginol/terrazzo/anchorage.jpg"},
    {"name": "Armadillo", "sku": "FB-4216", "file": "torginol/terrazzo/armadillo.jpg"},
    {"name": "Cascade", "sku": "FB-4207", "file": "torginol/terrazzo/cascade.jpg"},
    {"name": "Denali", "sku": "FB-4214", "file": "torginol/terrazzo/denali.jpg"},
    {"name": "Europa", "sku": "FB-4210", "file": "torginol/terrazzo/europa.jpg"},
    {"name": "Gumball", "sku": "FB-4209", "file": "torginol/terrazzo/gumball.jpg"},
    {"name": "Husky", "sku": "FB-4211", "file": "torginol/terrazzo/husky.jpg"},
    {"name": "Jawbreaker", "sku": "FB-4203", "file": "torginol/terrazzo/jawbreaker.jpg"},
    {"name": "Juneau", "sku": "FB-4205", "file": "torginol/terrazzo/juneau.jpg"},
    {"name": "Klondike", "sku": "FB-4206", "file": "torginol/terrazzo/klondike.jpg"},
    {"name": "Phoenix", "sku": "FB-4218", "file": "torginol/terrazzo/phoenix.jpg"},
    {"name": "Plateau", "sku": "FB-4201", "file": "torginol/terrazzo/plateau.jpg"},
    {"name": "Rosebud", "sku": "FB-4213", "file": "torginol/terrazzo/rosebud.jpg"},
    {"name": "Santa Fe", "sku": "FB-4217", "file": "torginol/terrazzo/santa-fe.jpg"},
    {"name": "Taffy", "sku": "FB-4219", "file": "torginol/terrazzo/taffy.jpg"},
    {"name": "Yosemite", "sku": "FB-4215", "file": "torginol/terrazzo/yosemite.jpg"},
    {"name": "Yukon", "sku": "FB-4212", "file": "torginol/terrazzo/yukon.jpg"},
  ] },
  { key: "hybrid-stone", title: "Hybrid Stone Collection", blurb: "Variegated chips that mimic granite and natural stone.", items: [
    {"name": "Agate", "sku": "FB-4107", "file": "torginol/hybrid-stone/agate.jpg"},
    {"name": "Blacktop", "sku": "FB-4112", "file": "torginol/hybrid-stone/blacktop.jpg"},
    {"name": "Blue Granite", "sku": "FB-4101", "file": "torginol/hybrid-stone/blue-granite.jpg"},
    {"name": "Claystone", "sku": "FB-4110", "file": "torginol/hybrid-stone/claystone.jpg"},
    {"name": "Limestone", "sku": "FB-4111", "file": "torginol/hybrid-stone/limestone.jpg"},
    {"name": "Mudstone", "sku": "FB-4109", "file": "torginol/hybrid-stone/mudstone.jpg"},
    {"name": "Quartzite", "sku": "FB-4102", "file": "torginol/hybrid-stone/quartzite.jpg"},
    {"name": "Sandstone", "sku": "FB-4108", "file": "torginol/hybrid-stone/sandstone.jpg"},
    {"name": "Shale", "sku": "FB-4106", "file": "torginol/hybrid-stone/shale.jpg"},
    {"name": "Slate", "sku": "FB-4105", "file": "torginol/hybrid-stone/slate.jpg"},
    {"name": "Travertine", "sku": "FB-4103", "file": "torginol/hybrid-stone/travertine.jpg"},
    {"name": "Turquoise", "sku": "FB-4104", "file": "torginol/hybrid-stone/turquoise.jpg"},
  ] },
  { key: "mosaic", title: "Mosaic Collection", blurb: "High-contrast mosaic blends with a hand-laid character.", items: [
    {"name": "Avant-garde", "sku": "FB-4405", "file": "torginol/mosaic/avant-garde.jpg"},
    {"name": "Balsam", "sku": "FB-4446", "file": "torginol/mosaic/balsam.jpg"},
    {"name": "Fountain", "sku": "FB-4449", "file": "torginol/mosaic/fountain.jpg"},
    {"name": "Mineral", "sku": "FB-4450", "file": "torginol/mosaic/mineral.jpg"},
    {"name": "Moxie", "sku": "FB-4448", "file": "torginol/mosaic/moxie.jpg"},
    {"name": "Nightshade", "sku": "FB-4451", "file": "torginol/mosaic/nightshade.jpg"},
    {"name": "Silken", "sku": "FB-4445", "file": "torginol/mosaic/silken.jpg"},
    {"name": "Silt", "sku": "FB-4452", "file": "torginol/mosaic/silt.jpg"},
    {"name": "Stratus", "sku": "FB-4447", "file": "torginol/mosaic/stratus.jpg"},
    {"name": "Syncopation", "sku": "FB-4404", "file": "torginol/mosaic/syncopation.jpg"},
  ] },
  { key: "insignia", title: "Insignia Collection", blurb: "Team-and-brand color blends \u2014 show your colors underfoot.", items: [
    {"name": "Beaver", "sku": "FB-217", "file": "flakes/beaver.jpg"},
    {"name": "Blitz", "sku": "FB-241", "file": "flakes/blitz.jpg"},
    {"name": "Boom", "sku": "FB-242", "file": "flakes/boom.jpg"},
    {"name": "Bucky", "sku": "FB-223", "file": "flakes/bucky.jpg"},
    {"name": "Charlotte", "sku": "FB-248", "file": "flakes/charlotte.jpg"},
    {"name": "Conquer", "sku": "FB-246", "file": "flakes/conquer.jpg"},
    {"name": "Flipper", "sku": "FB-236", "file": "flakes/flipper.jpg"},
    {"name": "Ford", "sku": "FB-213", "file": "flakes/ford.jpg"},
    {"name": "Freddie", "sku": "FB-256", "file": "flakes/freddie.jpg"},
    {"name": "Gold Rush", "sku": "FB-253", "file": "flakes/gold-rush.jpg"},
    {"name": "Green and Gold", "sku": "FB-982", "file": "flakes/green-and-gold.jpg"},
    {"name": "Growl", "sku": "FB-255", "file": "flakes/growl.jpg"},
    {"name": "Gumbo", "sku": "FB-238", "file": "flakes/gumbo.jpg"},
    {"name": "Jax", "sku": "FB-234", "file": "flakes/jax.jpg"},
    {"name": "LP Field", "sku": "FB-207", "file": "flakes/lp-field.jpg"},
    {"name": "Lincoln", "sku": "FB-229", "file": "flakes/lincoln.jpg"},
    {"name": "Milwaukee", "sku": "FB-231", "file": "flakes/milwaukee.jpg"},
    {"name": "Pat", "sku": "FB-250", "file": "flakes/pat.jpg"},
    {"name": "Poe", "sku": "FB-245", "file": "flakes/poe.jpg"},
    {"name": "Rampage", "sku": "FB-235", "file": "flakes/rampage.jpg"},
    {"name": "Rebel", "sku": "FB-251", "file": "flakes/rebel.jpg"},
    {"name": "Rise", "sku": "FB-247", "file": "flakes/rise.jpg"},
    {"name": "Roary", "sku": "FB-252", "file": "flakes/roary.jpg"},
    {"name": "Rowdy", "sku": "FB-249", "file": "flakes/rowdy.jpg"},
    {"name": "Skol", "sku": "FB-244", "file": "flakes/skol.jpg"},
    {"name": "Splash", "sku": "FB-237", "file": "flakes/splash.jpg"},
    {"name": "Steel City", "sku": "FB-240", "file": "flakes/steel-city.jpg"},
    {"name": "Swoop", "sku": "FB-239", "file": "flakes/swoop.jpg"},
    {"name": "Talon", "sku": "FB-257", "file": "flakes/talon.jpg"},
    {"name": "The Land", "sku": "FB-233", "file": "flakes/the-land.jpg"},
    {"name": "Tiger", "sku": "FB-254", "file": "flakes/tiger.jpg"},
    {"name": "Viktor", "sku": "FB-243", "file": "torginol/insignia/viktor.jpg"},
    {"name": "Whitewater", "sku": "FB-315", "file": "torginol/insignia/whitewater.jpg"},
    {"name": "Windy City", "sku": "FB-232", "file": "flakes/windy-city.jpg"},
  ] },
  { key: "mica-enhanced", title: "Mica-Enhanced", blurb: "Vinyl blends with natural mica for depth and sparkle.", items: [
    {"name": "Ammonite", "sku": "FB-5017", "file": "torginol/mica-enhanced/ammonite.jpg"},
    {"name": "Bronzite", "sku": "FB-5009", "file": "torginol/mica-enhanced/bronzite.jpg"},
    {"name": "Coastal", "sku": "FB-5022", "file": "torginol/mica-enhanced/coastal.jpg"},
    {"name": "Confetti", "sku": "FB-5003", "file": "torginol/mica-enhanced/confetti.jpg"},
    {"name": "Crescent Moon", "sku": "FB-5021", "file": "torginol/mica-enhanced/crescent-moon.jpg"},
    {"name": "Cyprus", "sku": "FB-5010", "file": "torginol/mica-enhanced/cyprus.jpg"},
    {"name": "Dusk", "sku": "FB-5020", "file": "torginol/mica-enhanced/dusk.jpg"},
    {"name": "Fireball", "sku": "FB-5001", "file": "torginol/mica-enhanced/fireball.jpg"},
    {"name": "Foundry", "sku": "FB-5304", "file": "torginol/mica-enhanced/foundry.jpg"},
    {"name": "Gemstone", "sku": "FB-5016", "file": "torginol/mica-enhanced/gemstone.jpg"},
    {"name": "Geode", "sku": "FB-5014", "file": "torginol/mica-enhanced/geode.jpg"},
    {"name": "Gilded", "sku": "FB-5301", "file": "torginol/mica-enhanced/gilded.jpg"},
    {"name": "Jazz", "sku": "FB-5002", "file": "torginol/mica-enhanced/jazz.jpg"},
    {"name": "Lava Rock", "sku": "FB-5012", "file": "torginol/mica-enhanced/lava-rock.jpg"},
    {"name": "Midnight Lagoon", "sku": "FB-5004", "file": "torginol/mica-enhanced/midnight-lagoon.jpg"},
    {"name": "New Penny", "sku": "FB-5302", "file": "torginol/mica-enhanced/new-penny.jpg"},
    {"name": "Onyx", "sku": "FB-5018", "file": "torginol/mica-enhanced/onyx.jpg"},
    {"name": "Peppercorn", "sku": "FB-5008", "file": "torginol/mica-enhanced/peppercorn.jpg"},
    {"name": "Pyrite", "sku": "FB-5015", "file": "torginol/mica-enhanced/pyrite.jpg"},
    {"name": "Russet", "sku": "FB-5303", "file": "torginol/mica-enhanced/russet.jpg"},
    {"name": "Sea Glass", "sku": "FB-5011", "file": "torginol/mica-enhanced/sea-glass.jpg"},
    {"name": "Sea Salt", "sku": "FB-5005", "file": "torginol/mica-enhanced/sea-salt.jpg"},
    {"name": "Smokestone", "sku": "FB-5007", "file": "torginol/mica-enhanced/smokestone.jpg"},
    {"name": "Tidepool", "sku": "FB-5019", "file": "torginol/mica-enhanced/tidepool.jpg"},
    {"name": "Treasure", "sku": "FB-5006", "file": "torginol/mica-enhanced/treasure.jpg"},
    {"name": "Whitecap", "sku": "FB-5013", "file": "torginol/mica-enhanced/whitecap.jpg"},
  ] },
  { key: "shimmer", title: "Shimmer & Glitter", blurb: "Reflective accents broadcast alone or over any blend.", items: [
    {"name": "Aurora Accent", "sku": "FB-3301", "file": "torginol/glitter/aurora-accent.jpg"},
    {"name": "Black (Hex)", "sku": "", "file": "torginol/glitter-hex/black.jpg"},
    {"name": "Black (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/black.jpg"},
    {"name": "Blue (Hex)", "sku": "", "file": "torginol/glitter-hex/blue.jpg"},
    {"name": "Bronze (Hex)", "sku": "", "file": "torginol/glitter-hex/bronze.jpg"},
    {"name": "Bronze (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/bronze.jpg"},
    {"name": "Brown (Hex)", "sku": "", "file": "torginol/glitter-hex/brown.jpg"},
    {"name": "Brown (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/brown.jpg"},
    {"name": "Copper (Hex)", "sku": "", "file": "torginol/glitter-hex/copper.jpg"},
    {"name": "Copper (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/copper.jpg"},
    {"name": "Creekbed Accent", "sku": "FB-715", "file": "torginol/glitter/creekbed-accent.jpg"},
    {"name": "Crystallina (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/crystallina.jpg"},
    {"name": "Dolerite Accent", "sku": "FB-9311", "file": "torginol/glitter/dolerite-accent.jpg"},
    {"name": "Domino Accent", "sku": "FB-411", "file": "torginol/glitter/domino-accent.jpg"},
    {"name": "Fuchsia (Hex)", "sku": "", "file": "torginol/glitter-hex/fuchsia.jpg"},
    {"name": "Gold (Hex)", "sku": "", "file": "torginol/glitter-hex/gold.jpg"},
    {"name": "Gold (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/gold.jpg"},
    {"name": "Green (Hex)", "sku": "", "file": "torginol/glitter-hex/green.jpg"},
    {"name": "Gunmetal (Hex)", "sku": "", "file": "torginol/glitter-hex/gunmetal.jpg"},
    {"name": "Gunmetal (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/gunmetal.jpg"},
    {"name": "Holographic (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/holographic.jpg"},
    {"name": "Madras Accent", "sku": "FB-706", "file": "torginol/glitter/madras-accent.jpg"},
    {"name": "Midnight (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/midnight.jpg"},
    {"name": "Nordic Green Accent", "sku": "FB-514", "file": "torginol/glitter/nordic-green-accent.jpg"},
    {"name": "Outback Accent", "sku": "FB-517", "file": "torginol/glitter/outback-accent.jpg"},
    {"name": "Red (Hex)", "sku": "", "file": "torginol/glitter-hex/red.jpg"},
    {"name": "Silver (Hex)", "sku": "", "file": "torginol/glitter-hex/silver.jpg"},
    {"name": "Silver (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/silver.jpg"},
    {"name": "Stargazer Accent", "sku": "FB-908", "file": "torginol/glitter/stargazer-accent.jpg"},
    {"name": "Stonehenge Accent", "sku": "FB-427", "file": "torginol/glitter/stonehenge-accent.jpg"},
    {"name": "Strudel Accent", "sku": "FB-502", "file": "torginol/glitter/strudel-accent.jpg"},
    {"name": "Victorian Accent", "sku": "FB-818", "file": "torginol/glitter/victorian-accent.jpg"},
    {"name": "White (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/white.jpg"},
    {"name": "Yellow (Hex)", "sku": "", "file": "torginol/glitter-hex/yellow.jpg"},
  ] },
  { key: "solid-colors", title: "Solid Colors", blurb: "Single-color flake \u2014 build your own custom blend ratio.", items: [
    {"name": "Acorn", "sku": "F5117", "file": "torginol/solid-colors/acorn.jpg"},
    {"name": "Adobe Beige", "sku": "F1000", "file": "torginol/solid-colors/adobe-beige.jpg"},
    {"name": "African Violet", "sku": "F5104", "file": "torginol/solid-colors/african-violet.jpg"},
    {"name": "Aloha Rose", "sku": "F3130", "file": "torginol/solid-colors/aloha-rose.jpg"},
    {"name": "Alpaca White", "sku": "F9958", "file": "torginol/solid-colors/alpaca-white.jpg"},
    {"name": "Amethyst", "sku": "F1020", "file": "torginol/solid-colors/amethyst.jpg"},
    {"name": "Antique White", "sku": "F9959", "file": "torginol/solid-colors/antique-white.jpg"},
    {"name": "Aquamarine", "sku": "F9952", "file": "torginol/solid-colors/aquamarine.jpg"},
    {"name": "Autumn Brown", "sku": "F1040", "file": "torginol/solid-colors/autumn-brown.jpg"},
    {"name": "Baby Blue", "sku": "F9988", "file": "torginol/solid-colors/baby-blue.jpg"},
    {"name": "Battleship Gray", "sku": "F9955", "file": "torginol/solid-colors/battleship-gray.jpg"},
    {"name": "Beige", "sku": "F1045", "file": "torginol/solid-colors/beige.jpg"},
    {"name": "Berry", "sku": "F9995", "file": "torginol/solid-colors/berry.jpg"},
    {"name": "Black", "sku": "F1050", "file": "torginol/solid-colors/black.jpg"},
    {"name": "Black Iron Oxide", "sku": "F9902", "file": "torginol/solid-colors/black-iron-oxide.jpg"},
    {"name": "Blue Ox", "sku": "F9907", "file": "torginol/solid-colors/blue-ox.jpg"},
    {"name": "Brown", "sku": "F1060", "file": "torginol/solid-colors/brown.jpg"},
    {"name": "Buff", "sku": "F6601", "file": "torginol/solid-colors/buff.jpg"},
    {"name": "Burgundy", "sku": "F1070", "file": "torginol/solid-colors/burgundy.jpg"},
    {"name": "Burnt Red", "sku": "F6609", "file": "torginol/solid-colors/burnt-red.jpg"},
    {"name": "Buttermilk", "sku": "F9910", "file": "torginol/solid-colors/buttermilk.jpg"},
    {"name": "Camelback", "sku": "F5307", "file": "torginol/solid-colors/camelback.jpg"},
    {"name": "Camo Green", "sku": "F6723", "file": "torginol/solid-colors/camo-green.jpg"},
    {"name": "Canyon Red", "sku": "F1080", "file": "torginol/solid-colors/canyon-red.jpg"},
    {"name": "Cappuccino", "sku": "F5303", "file": "torginol/solid-colors/cappuccino.jpg"},
    {"name": "Caramel", "sku": "F9954", "file": "torginol/solid-colors/caramel.jpg"},
    {"name": "Cardboard", "sku": "F5302", "file": "torginol/solid-colors/cardboard.jpg"},
    {"name": "Carrot Cake", "sku": "F9805", "file": "torginol/solid-colors/carrot-cake.jpg"},
    {"name": "Cement", "sku": "F5252", "file": "torginol/solid-colors/cement.jpg"},
    {"name": "Charcoal", "sku": "F1090", "file": "torginol/solid-colors/charcoal.jpg"},
    {"name": "Cherry Bomb", "sku": "F9920", "file": "torginol/solid-colors/cherry-bomb.jpg"},
    {"name": "Chiffon", "sku": "F9806", "file": "torginol/solid-colors/chiffon.jpg"},
    {"name": "Chocolate", "sku": "F5052", "file": "torginol/solid-colors/chocolate.jpg"},
    {"name": "Clay", "sku": "F6607", "file": "torginol/solid-colors/clay.jpg"},
    {"name": "Cobalt Blue", "sku": "F9963", "file": "torginol/solid-colors/cobalt-blue.jpg"},
    {"name": "Cocoa Brown", "sku": "F1100", "file": "torginol/solid-colors/cocoa-brown.jpg"},
    {"name": "Coppertone", "sku": "F9973", "file": "torginol/solid-colors/coppertone.jpg"},
    {"name": "Cornmeal", "sku": "F5301", "file": "torginol/solid-colors/cornmeal.jpg"},
    {"name": "Cosmo", "sku": "F9992", "file": "torginol/solid-colors/cosmo.jpg"},
    {"name": "Cream", "sku": "F6614", "file": "torginol/solid-colors/cream.jpg"},
    {"name": "Crest Green", "sku": "F1120", "file": "torginol/solid-colors/crest-green.jpg"},
    {"name": "Cyberspace", "sku": "F5920", "file": "torginol/solid-colors/cyberspace.jpg"},
    {"name": "Dark Blue", "sku": "F1130", "file": "torginol/solid-colors/dark-blue.jpg"},
    {"name": "Dark Brown", "sku": "F5501", "file": "torginol/solid-colors/dark-brown.jpg"},
    {"name": "Dark Gray", "sku": "F9904", "file": "torginol/solid-colors/dark-gray.jpg"},
    {"name": "Delray Blue", "sku": "F1140", "file": "torginol/solid-colors/delray-blue.jpg"},
    {"name": "Dolphin", "sku": "F9801", "file": "torginol/solid-colors/dolphin.jpg"},
    {"name": "Dove Gray", "sku": "F1160", "file": "torginol/solid-colors/dove-gray.jpg"},
    {"name": "Dusk Blue", "sku": "F1200", "file": "torginol/solid-colors/dusk-blue.jpg"},
    {"name": "Ebony", "sku": "F5114", "file": "torginol/solid-colors/ebony.jpg"},
    {"name": "Eggshell", "sku": "F9986", "file": "torginol/solid-colors/eggshell.jpg"},
    {"name": "Ewa Green", "sku": "F3020", "file": "torginol/solid-colors/ewa-green.jpg"},
    {"name": "Favre", "sku": "F9916", "file": "torginol/solid-colors/favre.jpg"},
    {"name": "Fawn", "sku": "F1320", "file": "torginol/solid-colors/fawn.jpg"},
    {"name": "Fireweed", "sku": "F5118", "file": "torginol/solid-colors/fireweed.jpg"},
    {"name": "Forest Green", "sku": "F1360", "file": "torginol/solid-colors/forest-green.jpg"},
    {"name": "Fossil", "sku": "F9911", "file": "torginol/solid-colors/fossil.jpg"},
    {"name": "Functional Gray", "sku": "F9961", "file": "torginol/solid-colors/functional-gray.jpg"},
    {"name": "Gardenview", "sku": "F9991", "file": "torginol/solid-colors/gardenview.jpg"},
    {"name": "Gladiola", "sku": "F6804", "file": "torginol/solid-colors/gladiola.jpg"},
    {"name": "Gold", "sku": "F1400", "file": "torginol/solid-colors/gold.jpg"},
    {"name": "Granite", "sku": "F1410", "file": "torginol/solid-colors/granite.jpg"},
    {"name": "Grape", "sku": "F9993", "file": "torginol/solid-colors/grape.jpg"},
    {"name": "Graphite", "sku": "F1415", "file": "torginol/solid-colors/graphite.jpg"},
    {"name": "Gravy", "sku": "F9982", "file": "torginol/solid-colors/gravy.jpg"},
    {"name": "Grounded", "sku": "F2518", "file": "torginol/solid-colors/grounded.jpg"},
    {"name": "Heaven", "sku": "F9905", "file": "torginol/solid-colors/heaven.jpg"},
    {"name": "Hunter Green", "sku": "F1420", "file": "torginol/solid-colors/hunter-green.jpg"},
    {"name": "Hypnotic", "sku": "F9983", "file": "torginol/solid-colors/hypnotic.jpg"},
    {"name": "Ivory", "sku": "F1425", "file": "torginol/solid-colors/ivory.jpg"},
    {"name": "JD Green", "sku": "F5910", "file": "torginol/solid-colors/jd-green.jpg"},
    {"name": "Jasper", "sku": "F1430", "file": "torginol/solid-colors/jasper.jpg"},
    {"name": "Jetstream", "sku": "F9962", "file": "torginol/solid-colors/jetstream.jpg"},
    {"name": "Khaki", "sku": "F9956", "file": "torginol/solid-colors/khaki.jpg"},
    {"name": "Kona Beige", "sku": "F3040", "file": "torginol/solid-colors/kona-beige.jpg"},
    {"name": "Latte", "sku": "F6602", "file": "torginol/solid-colors/latte.jpg"},
    {"name": "Lavender", "sku": "F9965", "file": "torginol/solid-colors/lavender.jpg"},
    {"name": "Lime", "sku": "F5102", "file": "torginol/solid-colors/lime.jpg"},
    {"name": "Lipstick Red", "sku": "F6721", "file": "torginol/solid-colors/lipstick-red.jpg"},
    {"name": "Maui Blue", "sku": "F3100", "file": "torginol/solid-colors/maui-blue.jpg"},
    {"name": "Medium Gray", "sku": "F1480", "file": "torginol/solid-colors/medium-gray.jpg"},
    {"name": "Milkweed", "sku": "F1520", "file": "torginol/solid-colors/milkweed.jpg"},
    {"name": "Mint Green", "sku": "F1560", "file": "torginol/solid-colors/mint-green.jpg"},
    {"name": "Moody Blue", "sku": "F9972", "file": "torginol/solid-colors/moody-blue.jpg"},
    {"name": "Moonshine", "sku": "F5201", "file": "torginol/solid-colors/moonshine.jpg"},
    {"name": "Morning Fog", "sku": "F9966", "file": "torginol/solid-colors/morning-fog.jpg"},
    {"name": "Moss", "sku": "F9970", "file": "torginol/solid-colors/moss.jpg"},
    {"name": "Mud", "sku": "F5304", "file": "torginol/solid-colors/mud.jpg"},
    {"name": "Mustard", "sku": "F1570", "file": "torginol/solid-colors/mustard.jpg"},
    {"name": "Navajo Beige", "sku": "F9960", "file": "torginol/solid-colors/navajo-beige.jpg"},
    {"name": "Navy", "sku": "F9969", "file": "torginol/solid-colors/navy.jpg"},
    {"name": "Neutral Gray", "sku": "F6606", "file": "torginol/solid-colors/neutral-gray.jpg"},
    {"name": "Oahu Brown", "sku": "F3000", "file": "torginol/solid-colors/oahu-brown.jpg"},
    {"name": "Olive", "sku": "F1600", "file": "torginol/solid-colors/olive.jpg"},
    {"name": "Online", "sku": "F9903", "file": "torginol/solid-colors/online.jpg"},
    {"name": "Orange", "sku": "F2160", "file": "torginol/solid-colors/orange.jpg"},
    {"name": "Pali Brown", "sku": "F3120", "file": "torginol/solid-colors/pali-brown.jpg"},
    {"name": "Patio Red", "sku": "F1640", "file": "torginol/solid-colors/patio-red.jpg"},
    {"name": "Peach", "sku": "F1680", "file": "torginol/solid-colors/peach.jpg"},
    {"name": "Peppermint", "sku": "F9971", "file": "torginol/solid-colors/peppermint.jpg"},
    {"name": "Plum", "sku": "F9951", "file": "torginol/solid-colors/plum.jpg"},
    {"name": "Porpoise", "sku": "F5306", "file": "torginol/solid-colors/porpoise.jpg"},
    {"name": "Potter", "sku": "F9981", "file": "torginol/solid-colors/potter.jpg"},
    {"name": "Powder Blue", "sku": "F1720", "file": "torginol/solid-colors/powder-blue.jpg"},
    {"name": "Primary Blue", "sku": "F6604", "file": "torginol/solid-colors/primary-blue.jpg"},
    {"name": "Primary Yellow", "sku": "F2200", "file": "torginol/solid-colors/primary-yellow.jpg"},
    {"name": "Purple Gray", "sku": "F2510", "file": "torginol/solid-colors/purple-gray.jpg"},
    {"name": "Purple Haze", "sku": "F9989", "file": "torginol/solid-colors/purple-haze.jpg"},
    {"name": "Putty", "sku": "F5115", "file": "torginol/solid-colors/putty.jpg"},
    {"name": "Raisin", "sku": "F9975", "file": "torginol/solid-colors/raisin.jpg"},
    {"name": "Red", "sku": "F2240", "file": "torginol/solid-colors/red.jpg"},
    {"name": "Redwood", "sku": "F9996", "file": "torginol/solid-colors/redwood.jpg"},
    {"name": "Rhino Gray", "sku": "F2563", "file": "torginol/solid-colors/rhino-gray.jpg"},
    {"name": "Rose", "sku": "F1760", "file": "torginol/solid-colors/rose.jpg"},
    {"name": "Royal Blue", "sku": "F9967", "file": "torginol/solid-colors/royal-blue.jpg"},
    {"name": "Rustic Red", "sku": "F5935", "file": "torginol/solid-colors/rustic-red.jpg"},
    {"name": "Sage", "sku": "F6613", "file": "torginol/solid-colors/sage.jpg"},
    {"name": "Salmon", "sku": "F1770", "file": "torginol/solid-colors/salmon.jpg"},
    {"name": "Sand Dune", "sku": "F9994", "file": "torginol/solid-colors/sand-dune.jpg"},
    {"name": "Scone", "sku": "F1780", "file": "torginol/solid-colors/scone.jpg"},
    {"name": "Seaspray", "sku": "F5101", "file": "torginol/solid-colors/seaspray.jpg"},
    {"name": "Semi-Transparent White", "sku": "F2250", "file": "torginol/solid-colors/semi-transparent-white.jpg"},
    {"name": "Sky Blue", "sku": "F9964", "file": "torginol/solid-colors/sky-blue.jpg"},
    {"name": "Slime", "sku": "F9990", "file": "torginol/solid-colors/slime.jpg"},
    {"name": "Sommelier", "sku": "F9800", "file": "torginol/solid-colors/sommelier.jpg"},
    {"name": "Sonic", "sku": "F9984", "file": "torginol/solid-colors/sonic.jpg"},
    {"name": "Sorbet", "sku": "F5103", "file": "torginol/solid-colors/sorbet.jpg"},
    {"name": "Space Gray", "sku": "F5182", "file": "torginol/solid-colors/space-gray.jpg"},
    {"name": "Squash", "sku": "F9979", "file": "torginol/solid-colors/squash.jpg"},
    {"name": "Steel Blue", "sku": "F9968", "file": "torginol/solid-colors/steel-blue.jpg"},
    {"name": "Sticks &amp; Stones", "sku": "F5219", "file": "torginol/solid-colors/sticks-amp-stones.jpg"},
    {"name": "Stone", "sku": "F9987", "file": "torginol/solid-colors/stone.jpg"},
    {"name": "Stormy Blue", "sku": "F6621", "file": "torginol/solid-colors/stormy-blue.jpg"},
    {"name": "Sugar Cookie", "sku": "F9909", "file": "torginol/solid-colors/sugar-cookie.jpg"},
    {"name": "Sunrise Yellow", "sku": "F6622", "file": "torginol/solid-colors/sunrise-yellow.jpg"},
    {"name": "Tabu", "sku": "F5305", "file": "torginol/solid-colors/tabu.jpg"},
    {"name": "Tan", "sku": "F1785", "file": "torginol/solid-colors/tan.jpg"},
    {"name": "Taupe", "sku": "F9957", "file": "torginol/solid-colors/taupe.jpg"},
    {"name": "Teal", "sku": "F6617", "file": "torginol/solid-colors/teal.jpg"},
    {"name": "Terra Cotta", "sku": "F7551", "file": "torginol/solid-colors/terra-cotta.jpg"},
    {"name": "Toast", "sku": "F9912", "file": "torginol/solid-colors/toast.jpg"},
    {"name": "Tomato", "sku": "F9978", "file": "torginol/solid-colors/tomato.jpg"},
    {"name": "True Blue", "sku": "F1790", "file": "torginol/solid-colors/true-blue.jpg"},
    {"name": "Whisper Gray", "sku": "F1800", "file": "torginol/solid-colors/whisper-gray.jpg"},
    {"name": "White", "sku": "F1820", "file": "torginol/solid-colors/white.jpg"},
    {"name": "Wigwam", "sku": "F5116", "file": "torginol/solid-colors/wigwam.jpg"},
  ] },
  { key: "archive", title: "Classic Archive", blurb: "Long-running classics from the Torginol archive, available special-order.", items: [
    {"name": "Almond", "sku": "FB-605", "file": "torginol/archive/almond.jpg"},
    {"name": "Alpine", "sku": "FB-103", "file": "torginol/archive/alpine.jpg"},
    {"name": "Appalachian", "sku": "FB-812", "file": "torginol/archive/appalachian.jpg"},
    {"name": "Arctic", "sku": "FB-704", "file": "flakes/arctic.jpg"},
    {"name": "Argyle", "sku": "FB-303", "file": "torginol/archive/argyle.jpg"},
    {"name": "Baboon", "sku": "FB-964", "file": "torginol/archive/baboon.jpg"},
    {"name": "Bandit", "sku": "FB-126", "file": "torginol/archive/bandit.jpg"},
    {"name": "Barn Owl", "sku": "FB-1004", "file": "torginol/archive/barn-owl.jpg"},
    {"name": "Barrel", "sku": "FB-110", "file": "torginol/archive/barrel.jpg"},
    {"name": "Basil", "sku": "FB-418", "file": "torginol/archive/basil.jpg"},
    {"name": "Basset", "sku": "FB-105", "file": "torginol/archive/basset.jpg"},
    {"name": "Beachcomber", "sku": "FB-603", "file": "torginol/archive/beachcomber.jpg"},
    {"name": "Beast", "sku": "FB-955", "file": "torginol/archive/beast.jpg"},
    {"name": "Belle", "sku": "FB-124", "file": "torginol/archive/belle.jpg"},
    {"name": "Birch Bark", "sku": "FB-1005", "file": "flakes/birch-bark.jpg"},
    {"name": "Birthday Cake", "sku": "FB-816", "file": "torginol/archive/birthday-cake.jpg"},
    {"name": "Blue Heron", "sku": "FB-1006", "file": "torginol/archive/blue-heron.jpg"},
    {"name": "Blue Lagoon", "sku": "FB-819", "file": "torginol/archive/blue-lagoon.jpg"},
    {"name": "Blue Wing", "sku": "FB-116", "file": "torginol/archive/blue-wing.jpg"},
    {"name": "Briar", "sku": "FB-221", "file": "flakes/briar.jpg"},
    {"name": "Brookside", "sku": "FB-117", "file": "torginol/archive/brookside.jpg"},
    {"name": "Brown Sugar", "sku": "FB-961", "file": "torginol/archive/brown-sugar.jpg"},
    {"name": "Buckskin", "sku": "FB-614", "file": "torginol/archive/buckskin.jpg"},
    {"name": "Burlap", "sku": "FB-417", "file": "torginol/archive/burlap.jpg"},
    {"name": "Burlwood", "sku": "FB-305", "file": "torginol/archive/burlwood.jpg"},
    {"name": "Cam", "sku": "FB-206", "file": "flakes/cam.jpg"},
    {"name": "Camel", "sku": "FB-413", "file": "torginol/archive/camel.jpg"},
    {"name": "Cannoli", "sku": "FB-130", "file": "flakes/cannoli.jpg"},
    {"name": "Cardinal", "sku": "FB-230", "file": "flakes/cardinal.jpg"},
    {"name": "Carey", "sku": "FB-227", "file": "flakes/carey.jpg"},
    {"name": "Caribou", "sku": "FB-104", "file": "torginol/archive/caribou.jpg"},
    {"name": "Cashmere", "sku": "FB-129", "file": "torginol/archive/cashmere.jpg"},
    {"name": "Cato", "sku": "FB-121", "file": "torginol/archive/cato.jpg"},
    {"name": "Cedar", "sku": "FB-815", "file": "torginol/archive/cedar.jpg"},
    {"name": "Chameleon", "sku": "FB-309", "file": "torginol/archive/chameleon.jpg"},
    {"name": "Chestnut", "sku": "FB-822", "file": "torginol/archive/chestnut.jpg"},
    {"name": "Cleveland Chomps", "sku": "FB-205", "file": "torginol/archive/cleveland-chomps.jpg"},
    {"name": "Clover", "sku": "FB-808", "file": "torginol/archive/clover.jpg"},
    {"name": "Cobblestone", "sku": "FB-422", "file": "torginol/archive/cobblestone.jpg"},
    {"name": "Coliseum", "sku": "FB-216", "file": "flakes/coliseum.jpg"},
    {"name": "Colonial", "sku": "FB-817", "file": "flakes/colonial.jpg"},
    {"name": "Crimson", "sku": "FB-123", "file": "torginol/archive/crimson.jpg"},
    {"name": "Cruller", "sku": "FB-820", "file": "torginol/archive/cruller.jpg"},
    {"name": "Dahlia", "sku": "FB-308", "file": "torginol/archive/dahlia.jpg"},
    {"name": "Dakota Trail", "sku": "FB-607", "file": "torginol/archive/dakota-trail.jpg"},
    {"name": "Danish", "sku": "FB-118", "file": "torginol/archive/danish.jpg"},
    {"name": "Daredevil", "sku": "FB-220", "file": "flakes/daredevil.jpg"},
    {"name": "Doak", "sku": "FB-212", "file": "flakes/doak.jpg"},
    {"name": "Dory", "sku": "FB-307", "file": "torginol/archive/dory.jpg"},
    {"name": "Everbank", "sku": "FB-226", "file": "flakes/everbank.jpg"},
    {"name": "Fern", "sku": "FB-102", "file": "torginol/archive/fern.jpg"},
    {"name": "Finch", "sku": "FB-106", "file": "torginol/archive/finch.jpg"},
    {"name": "Fireside", "sku": "FB-604", "file": "torginol/archive/fireside.jpg"},
    {"name": "Fox", "sku": "FB-120", "file": "torginol/archive/fox.jpg"},
    {"name": "Fritter", "sku": "FB-101", "file": "torginol/archive/fritter.jpg"},
    {"name": "Gale", "sku": "FB-301", "file": "torginol/archive/gale.jpg"},
    {"name": "Gargoyle", "sku": "FB-914", "file": "flakes/gargoyle.jpg"},
    {"name": "Grasshopper", "sku": "FB-813", "file": "torginol/archive/grasshopper.jpg"},
    {"name": "Green Bay", "sku": "FB-426", "file": "torginol/archive/green-bay.jpg"},
    {"name": "Grizzly", "sku": "FB-965", "file": "torginol/archive/grizzly.jpg"},
    {"name": "Harvest", "sku": "FB-412", "file": "torginol/archive/harvest.jpg"},
    {"name": "Heinz", "sku": "FB-209", "file": "flakes/heinz.jpg"},
    {"name": "Hillside", "sku": "FB-701", "file": "torginol/archive/hillside.jpg"},
    {"name": "Himalayan", "sku": "FB-705", "file": "torginol/archive/himalayan.jpg"},
    {"name": "Honeycomb", "sku": "FB-957", "file": "torginol/archive/honeycomb.jpg"},
    {"name": "Huckleberry", "sku": "FB-311", "file": "torginol/archive/huckleberry.jpg"},
    {"name": "Humphrey", "sku": "FB-225", "file": "flakes/humphrey.jpg"},
    {"name": "Ice Blue", "sku": "FB-425", "file": "torginol/archive/ice-blue.jpg"},
    {"name": "Iceberg", "sku": "FB-702", "file": "torginol/archive/iceberg.jpg"},
    {"name": "Imperial", "sku": "FB-329", "file": "torginol/archive/imperial.jpg"},
    {"name": "Iris", "sku": "FB-316", "file": "torginol/archive/iris.jpg"},
    {"name": "Kalahari", "sku": "FB-519", "file": "torginol/archive/kalahari.jpg"},
    {"name": "Kennedy", "sku": "FB-115", "file": "torginol/archive/kennedy.jpg"},
    {"name": "Khaki", "sku": "FB-428", "file": "torginol/archive/khaki.jpg"},
    {"name": "Kringle", "sku": "FB-515", "file": "torginol/archive/kringle.jpg"},
    {"name": "Lambeau", "sku": "FB-201", "file": "flakes/lambeau.jpg"},
    {"name": "Leopard", "sku": "FB-518", "file": "torginol/archive/leopard.jpg"},
    {"name": "Lighthouse", "sku": "FB-302", "file": "torginol/archive/lighthouse.jpg"},
    {"name": "Linden", "sku": "FB-963", "file": "torginol/archive/linden.jpg"},
    {"name": "Lucas", "sku": "FB-218", "file": "flakes/lucas.jpg"},
    {"name": "Lunar", "sku": "FB-904", "file": "flakes/lunar.jpg"},
    {"name": "Madden", "sku": "FB-214", "file": "flakes/madden.jpg"},
    {"name": "Maple Grove", "sku": "FB-323", "file": "torginol/archive/maple-grove.jpg"},
    {"name": "Mardi Gras", "sku": "FB-317", "file": "torginol/archive/mardi-gras.jpg"},
    {"name": "Matador", "sku": "FB-505", "file": "torginol/archive/matador.jpg"},
    {"name": "Merlot", "sku": "FB-416", "file": "torginol/archive/merlot.jpg"},
    {"name": "Metrodome", "sku": "FB-215", "file": "flakes/metrodome.jpg"},
    {"name": "Midnight", "sku": "FB-423", "file": "torginol/archive/midnight.jpg"},
    {"name": "Miller", "sku": "FB-208", "file": "flakes/miller.jpg"},
    {"name": "Mink", "sku": "FB-109", "file": "torginol/archive/mink.jpg"},
    {"name": "Mojito", "sku": "FB-958", "file": "torginol/archive/mojito.jpg"},
    {"name": "Monroe", "sku": "FB-107", "file": "torginol/archive/monroe.jpg"},
    {"name": "Montana", "sku": "FB-224", "file": "flakes/montana.jpg"},
    {"name": "Monterrey", "sku": "FB-809", "file": "torginol/archive/monterrey.jpg"},
    {"name": "Morning Dew", "sku": "FB-609", "file": "flakes/morning-dew.jpg"},
    {"name": "Morocco", "sku": "FB-810", "file": "torginol/archive/morocco.jpg"},
    {"name": "Moth", "sku": "FB-1001", "file": "torginol/archive/moth.jpg"},
    {"name": "Mountain Green", "sku": "FB-322", "file": "torginol/archive/mountain-green.jpg"},
    {"name": "Mudslide", "sku": "FB-108", "file": "torginol/archive/mudslide.jpg"},
    {"name": "Oasis", "sku": "FB-712", "file": "flakes/oasis.jpg"},
    {"name": "Olivine", "sku": "FB-710", "file": "torginol/archive/olivine.jpg"},
    {"name": "Oregano", "sku": "FB-111", "file": "torginol/archive/oregano.jpg"},
    {"name": "Palomino", "sku": "FB-804", "file": "torginol/archive/palomino.jpg"},
    {"name": "Papillion", "sku": "FB-119", "file": "torginol/archive/papillion.jpg"},
    {"name": "Paul Brown", "sku": "FB-204", "file": "flakes/paul-brown.jpg"},
    {"name": "Pecan", "sku": "FB-125", "file": "torginol/archive/pecan.jpg"},
    {"name": "Pembrook", "sku": "FB-114", "file": "torginol/archive/pembrook.jpg"},
    {"name": "Persian", "sku": "FB-952", "file": "torginol/archive/persian.jpg"},
    {"name": "Pheasant", "sku": "FB-318", "file": "torginol/archive/pheasant.jpg"},
    {"name": "Pintail", "sku": "FB-324", "file": "torginol/archive/pintail.jpg"},
    {"name": "Portico", "sku": "FB-707", "file": "torginol/archive/portico.jpg"},
    {"name": "Portobello", "sku": "FB-512", "file": "torginol/archive/portobello.jpg"},
    {"name": "Prairie", "sku": "FB-509", "file": "torginol/archive/prairie.jpg"},
    {"name": "Primrose", "sku": "FB-128", "file": "torginol/archive/primrose.jpg"},
    {"name": "Ram", "sku": "FB-210", "file": "flakes/ram.jpg"},
    {"name": "Rapids", "sku": "FB-506", "file": "flakes/rapids.jpg"},
    {"name": "Reliant", "sku": "FB-222", "file": "flakes/reliant.jpg"},
    {"name": "Rescue Ranger", "sku": "FB-122", "file": "torginol/archive/rescue-ranger.jpg"},
    {"name": "River Rock", "sku": "FB-1002", "file": "torginol/archive/river-rock.jpg"},
    {"name": "Sand Dollar", "sku": "FB-951", "file": "flakes/sand-dollar.jpg"},
    {"name": "Savannah", "sku": "FB-814", "file": "torginol/archive/savannah.jpg"},
    {"name": "Scarecrow", "sku": "FB-615", "file": "torginol/archive/scarecrow.jpg"},
    {"name": "Sea Crest", "sku": "FB-803", "file": "flakes/sea-crest.jpg"},
    {"name": "Sea Mist", "sku": "FB-802", "file": "flakes/sea-mist.jpg"},
    {"name": "Seaport", "sku": "FB-709", "file": "torginol/archive/seaport.jpg"},
    {"name": "Setter", "sku": "FB-953", "file": "torginol/archive/setter.jpg"},
    {"name": "Siberian", "sku": "FB-902", "file": "flakes/siberian.jpg"},
    {"name": "Sierra", "sku": "FB-321", "file": "torginol/archive/sierra.jpg"},
    {"name": "Smokehouse", "sku": "FB-306", "file": "torginol/archive/smokehouse.jpg"},
    {"name": "Soldier", "sku": "FB-202", "file": "flakes/soldier.jpg"},
    {"name": "Space Odyssey", "sku": "FB-312", "file": "torginol/archive/space-odyssey.jpg"},
    {"name": "Spangle", "sku": "FB-219", "file": "flakes/spangle.jpg"},
    {"name": "Spice", "sku": "FB-610", "file": "torginol/archive/spice.jpg"},
    {"name": "Stinger", "sku": "FB-508", "file": "flakes/stinger.jpg"},
    {"name": "Strudel", "sku": "FB-502", "file": "torginol/archive/strudel.jpg"},
    {"name": "Submarine", "sku": "FB-608", "file": "flakes/submarine.jpg"},
    {"name": "Sun Life", "sku": "FB-203", "file": "flakes/sun-life.jpg"},
    {"name": "Sunset Beige", "sku": "FB-112", "file": "torginol/archive/sunset-beige.jpg"},
    {"name": "Superdome", "sku": "FB-211", "file": "flakes/superdome.jpg"},
    {"name": "Terrier", "sku": "FB-325", "file": "torginol/archive/terrier.jpg"},
    {"name": "Thistle", "sku": "FB-510", "file": "torginol/archive/thistle.jpg"},
    {"name": "Twine", "sku": "FB-956", "file": "torginol/archive/twine.jpg"},
    {"name": "Victorian", "sku": "FB-818", "file": "flakes/victorian.jpg"},
    {"name": "Washington", "sku": "FB-228", "file": "flakes/washington.jpg"},
    {"name": "Welsch", "sku": "FB-805", "file": "torginol/archive/welsch.jpg"},
    {"name": "Willow", "sku": "FB-511", "file": "torginol/archive/willow.jpg"},
    {"name": "Winter Wren", "sku": "FB-1003", "file": "torginol/archive/winter-wren.jpg"},
    {"name": "Yorkshire", "sku": "FB-501", "file": "torginol/archive/yorkshire.jpg"},
    {"name": "\u00c9clair", "sku": "FB-326", "file": "torginol/archive/eclair.jpg"},
  ] },
];

export default COLLECTIONS;
