// AUTO-GENERATED 2026-06-11 from the torginol.com product catalog (828 product pages).
// Images live in src/images/flakes/ (legacy) and src/images/torginol/<collection>/ (gitignored, exist locally).
// To refresh: re-run the sitemap crawl + download described in docs/superpowers/specs/2026-06-11-visual-redesign-design.md.
const COLLECTIONS = [
  { key: "signature", title: "Signature Collection", blurb: "Torginol's flagship blends \u2014 the most popular looks in epoxy flooring.", items: [
    {"name": "Cabin Fever", "sku": "FB-127", "file": "flakes/cabin-fever.webp"},
    {"name": "Creekbed", "sku": "FB-716", "file": "flakes/creekbed.webp"},
    {"name": "Domino", "sku": "FB-411", "file": "flakes/domino.webp"},
    {"name": "Gracious", "sku": "FB-916", "file": "flakes/gracious.webp"},
    {"name": "Gravel", "sku": "FB-414", "file": "flakes/gravel.webp"},
    {"name": "Nightfall", "sku": "FB-715", "file": "flakes/nightfall.webp"},
    {"name": "Orbit", "sku": "FB-310", "file": "flakes/orbit.webp"},
    {"name": "Outback", "sku": "FB-517", "file": "flakes/outback.webp"},
    {"name": "Shoreline", "sku": "FB-421", "file": "flakes/shoreline.webp"},
    {"name": "Tidal Wave", "sku": "FB-807", "file": "flakes/tidal-wave.webp"},
    {"name": "Wombat", "sku": "FB-616", "file": "flakes/wombat.webp"},
  ] },
  { key: "garage", title: "Garage Collection", blurb: "Purpose-built blends that hide dust, dirt, and tire marks in working garages.", items: [
    {"name": "Bean", "sku": "FB-960", "file": "torginol/garage/bean.webp"},
    {"name": "Comet", "sku": "FB-711", "file": "flakes/comet.webp"},
    {"name": "Crossbow", "sku": "FB-320", "file": "flakes/crossbow.webp"},
    {"name": "Hog", "sku": "FB-606", "file": "torginol/garage/hog.webp"},
    {"name": "Platteville", "sku": "FB-314", "file": "torginol/garage/platteville.webp"},
    {"name": "Quicksilver", "sku": "FB-424", "file": "flakes/quicksilver.webp"},
    {"name": "Stonehenge", "sku": "FB-427", "file": "flakes/stonehenge.webp"},
    {"name": "Stonewash", "sku": "FB-708", "file": "flakes/stonewash.webp"},
    {"name": "Yellow Jacket", "sku": "FB-332", "file": "torginol/garage/yellow-jacket.webp"},
  ] },
  { key: "contemporary", title: "Contemporary Collection", blurb: "Clean, modern palettes for living spaces and showrooms.", items: [
    {"name": "Antler", "sku": "FB-601", "file": "torginol/contemporary/antler.webp"},
    {"name": "Chenille", "sku": "FB-981", "file": "flakes/chenille.webp"},
    {"name": "Citrine", "sku": "FB-978", "file": "flakes/citrine.webp"},
    {"name": "Coyote", "sku": "FB-513", "file": "flakes/coyote.webp"},
    {"name": "Dingo", "sku": "FB-980", "file": "flakes/dingo.webp"},
    {"name": "Dovetail", "sku": "FB-823", "file": "flakes/dovetail.webp"},
    {"name": "Heron", "sku": "FB-976", "file": "flakes/heron.webp"},
    {"name": "Keystone", "sku": "FB-713", "file": "flakes/keystone.webp"},
    {"name": "Koala", "sku": "FB-811", "file": "flakes/koala.webp"},
    {"name": "Madras", "sku": "FB-706", "file": "flakes/madras.webp"},
    {"name": "Morel", "sku": "FB-979", "file": "flakes/morel.webp"},
    {"name": "Nordic Green", "sku": "FB-514", "file": "flakes/nordic-green.webp"},
    {"name": "Polar", "sku": "FB-330", "file": "flakes/polar.webp"},
    {"name": "Reed", "sku": "FB-507", "file": "flakes/reed.webp"},
    {"name": "Rocky Ridge", "sku": "FB-801", "file": "flakes/rocky-ridge.webp"},
    {"name": "Stony Creek", "sku": "FB-806", "file": "flakes/stony-creek.webp"},
    {"name": "Thyme", "sku": "FB-977", "file": "flakes/thyme.webp"},
  ] },
  { key: "marble", title: "Marble Collection", blurb: "Soft, stone-inspired tones with a natural marbled read.", items: [
    {"name": "Arkose", "sku": "F9318", "file": "flakes/arkose.webp"},
    {"name": "Basalt", "sku": "F9309", "file": "flakes/basalt.webp"},
    {"name": "Blizzard", "sku": "FB-6001", "file": "flakes/blizzard.webp"},
    {"name": "Carbon", "sku": "F9202", "file": "flakes/carbon.webp"},
    {"name": "Dolerite", "sku": "F9311", "file": "flakes/dolerite.webp"},
    {"name": "Feldspar", "sku": "F9203", "file": "flakes/feldspar.webp"},
    {"name": "Garnet", "sku": "F9305", "file": "flakes/garnet.webp"},
    {"name": "Lanai Gray", "sku": "F3080", "file": "torginol/marble/lanai-gray.webp"},
    {"name": "Metapelite", "sku": "F9317", "file": "flakes/metapelite.webp"},
    {"name": "Obsidian", "sku": "F9304", "file": "flakes/obsidian.webp"},
    {"name": "Pumice", "sku": "F9303", "file": "flakes/pumice.webp"},
    {"name": "Sable", "sku": "F9205", "file": "flakes/sable.webp"},
    {"name": "Schist", "sku": "F9307", "file": "flakes/schist.webp"},
    {"name": "Soapstone", "sku": "F9320", "file": "flakes/soapstone.webp"},
    {"name": "Spilite", "sku": "F9313", "file": "flakes/spilite.webp"},
    {"name": "Sycamore", "sku": "FB-6002", "file": "flakes/sycamore.webp"},
    {"name": "Talus", "sku": "F9319", "file": "flakes/talus.webp"},
    {"name": "Weathered Gray", "sku": "FB-6003", "file": "flakes/weathered-gray.webp"},
  ] },
  { key: "brownstone", title: "Brownstone Collection", blurb: "Warm earth tones \u2014 tans, browns, and desert neutrals.", items: [
    {"name": "Bambi", "sku": "FB-959", "file": "flakes/bambi.webp"},
    {"name": "Buffalo", "sku": "FB-954", "file": "flakes/buffalo.webp"},
    {"name": "Chickadee", "sku": "FB-967", "file": "flakes/chickadee.webp"},
    {"name": "Coldwater Canyon", "sku": "FB-304", "file": "torginol/brownstone/coldwater-canyon.webp"},
    {"name": "Loon", "sku": "FB-966", "file": "flakes/loon.webp"},
    {"name": "Merino", "sku": "FB-971", "file": "flakes/merino.webp"},
    {"name": "Mushroom", "sku": "FB-714", "file": "flakes/mushroom.webp"},
    {"name": "Quail", "sku": "FB-974", "file": "flakes/quail.webp"},
    {"name": "Robin", "sku": "FB-973", "file": "flakes/robin.webp"},
    {"name": "Rosy-Finch", "sku": "FB-969", "file": "flakes/rosy-finch.webp"},
    {"name": "Safari", "sku": "FB-504", "file": "flakes/safari.webp"},
    {"name": "Sparrow", "sku": "FB-972", "file": "flakes/sparrow.webp"},
    {"name": "Swan", "sku": "FB-612", "file": "flakes/swan.webp"},
    {"name": "Trailmix", "sku": "FB-613", "file": "torginol/brownstone/trailmix.webp"},
    {"name": "Waxwing", "sku": "FB-968", "file": "flakes/waxwing.webp"},
    {"name": "Woodland", "sku": "FB-516", "file": "flakes/woodland.webp"},
    {"name": "Woodpecker", "sku": "FB-975", "file": "flakes/woodpecker.webp"},
    {"name": "Wren", "sku": "FB-970", "file": "flakes/wren.webp"},
  ] },
  { key: "greystone", title: "Greystone Collection", blurb: "Cool greys from light fog to deep charcoal.", items: [
    {"name": "Feather Gray", "sku": "FB-905", "file": "flakes/feather-gray.webp"},
    {"name": "Fog", "sku": "FB-703", "file": "flakes/fog.webp"},
    {"name": "Galaxy", "sku": "FB-907", "file": "flakes/galaxy.webp"},
    {"name": "Houndstooth", "sku": "FB-910", "file": "flakes/houndstooth.webp"},
    {"name": "Moon Mist", "sku": "FB-906", "file": "flakes/moon-mist.webp"},
    {"name": "Opal", "sku": "FB-901", "file": "flakes/opal.webp"},
    {"name": "Raven", "sku": "FB-915", "file": "flakes/raven.webp"},
    {"name": "Shadow", "sku": "FB-913", "file": "flakes/shadow.webp"},
    {"name": "Silver Bells", "sku": "FB-903", "file": "flakes/silver-bells.webp"},
    {"name": "Snowfall", "sku": "FB-602", "file": "flakes/snowfall.webp"},
    {"name": "Stargazer", "sku": "FB-908", "file": "flakes/stargazer.webp"},
    {"name": "Thunder", "sku": "FB-912", "file": "flakes/thunder.webp"},
    {"name": "Timberwolf", "sku": "FB-909", "file": "flakes/timberwolf.webp"},
    {"name": "Wild Dove", "sku": "FB-911", "file": "flakes/wild-dove.webp"},
  ] },
  { key: "terrazzo", title: "Terrazzo Collection", blurb: "Bold terrazzo-style chips for a classic composite look.", items: [
    {"name": "Acadia", "sku": "FB-4208", "file": "torginol/terrazzo/acadia.webp"},
    {"name": "Alameda", "sku": "FB-4202", "file": "torginol/terrazzo/alameda.webp"},
    {"name": "Anchorage", "sku": "FB-4204", "file": "torginol/terrazzo/anchorage.webp"},
    {"name": "Armadillo", "sku": "FB-4216", "file": "torginol/terrazzo/armadillo.webp"},
    {"name": "Cascade", "sku": "FB-4207", "file": "torginol/terrazzo/cascade.webp"},
    {"name": "Denali", "sku": "FB-4214", "file": "torginol/terrazzo/denali.webp"},
    {"name": "Europa", "sku": "FB-4210", "file": "torginol/terrazzo/europa.webp"},
    {"name": "Gumball", "sku": "FB-4209", "file": "torginol/terrazzo/gumball.webp"},
    {"name": "Husky", "sku": "FB-4211", "file": "torginol/terrazzo/husky.webp"},
    {"name": "Jawbreaker", "sku": "FB-4203", "file": "torginol/terrazzo/jawbreaker.webp"},
    {"name": "Juneau", "sku": "FB-4205", "file": "torginol/terrazzo/juneau.webp"},
    {"name": "Klondike", "sku": "FB-4206", "file": "torginol/terrazzo/klondike.webp"},
    {"name": "Phoenix", "sku": "FB-4218", "file": "torginol/terrazzo/phoenix.webp"},
    {"name": "Plateau", "sku": "FB-4201", "file": "torginol/terrazzo/plateau.webp"},
    {"name": "Rosebud", "sku": "FB-4213", "file": "torginol/terrazzo/rosebud.webp"},
    {"name": "Santa Fe", "sku": "FB-4217", "file": "torginol/terrazzo/santa-fe.webp"},
    {"name": "Taffy", "sku": "FB-4219", "file": "torginol/terrazzo/taffy.webp"},
    {"name": "Yosemite", "sku": "FB-4215", "file": "torginol/terrazzo/yosemite.webp"},
    {"name": "Yukon", "sku": "FB-4212", "file": "torginol/terrazzo/yukon.webp"},
  ] },
  { key: "hybrid-stone", title: "Hybrid Stone Collection", blurb: "Variegated chips that mimic granite and natural stone.", items: [
    {"name": "Agate", "sku": "FB-4107", "file": "torginol/hybrid-stone/agate.webp"},
    {"name": "Blacktop", "sku": "FB-4112", "file": "torginol/hybrid-stone/blacktop.webp"},
    {"name": "Blue Granite", "sku": "FB-4101", "file": "torginol/hybrid-stone/blue-granite.webp"},
    {"name": "Claystone", "sku": "FB-4110", "file": "torginol/hybrid-stone/claystone.webp"},
    {"name": "Limestone", "sku": "FB-4111", "file": "torginol/hybrid-stone/limestone.webp"},
    {"name": "Mudstone", "sku": "FB-4109", "file": "torginol/hybrid-stone/mudstone.webp"},
    {"name": "Quartzite", "sku": "FB-4102", "file": "torginol/hybrid-stone/quartzite.webp"},
    {"name": "Sandstone", "sku": "FB-4108", "file": "torginol/hybrid-stone/sandstone.webp"},
    {"name": "Shale", "sku": "FB-4106", "file": "torginol/hybrid-stone/shale.webp"},
    {"name": "Slate", "sku": "FB-4105", "file": "torginol/hybrid-stone/slate.webp"},
    {"name": "Travertine", "sku": "FB-4103", "file": "torginol/hybrid-stone/travertine.webp"},
    {"name": "Turquoise", "sku": "FB-4104", "file": "torginol/hybrid-stone/turquoise.webp"},
  ] },
  { key: "mosaic", title: "Mosaic Collection", blurb: "High-contrast mosaic blends with a hand-laid character.", items: [
    {"name": "Avant-garde", "sku": "FB-4405", "file": "torginol/mosaic/avant-garde.webp"},
    {"name": "Balsam", "sku": "FB-4446", "file": "torginol/mosaic/balsam.webp"},
    {"name": "Fountain", "sku": "FB-4449", "file": "torginol/mosaic/fountain.webp"},
    {"name": "Mineral", "sku": "FB-4450", "file": "torginol/mosaic/mineral.webp"},
    {"name": "Moxie", "sku": "FB-4448", "file": "torginol/mosaic/moxie.webp"},
    {"name": "Nightshade", "sku": "FB-4451", "file": "torginol/mosaic/nightshade.webp"},
    {"name": "Silken", "sku": "FB-4445", "file": "torginol/mosaic/silken.webp"},
    {"name": "Silt", "sku": "FB-4452", "file": "torginol/mosaic/silt.webp"},
    {"name": "Stratus", "sku": "FB-4447", "file": "torginol/mosaic/stratus.webp"},
    {"name": "Syncopation", "sku": "FB-4404", "file": "torginol/mosaic/syncopation.webp"},
  ] },
  { key: "insignia", title: "Insignia Collection", blurb: "Team-and-brand color blends \u2014 show your colors underfoot.", items: [
    {"name": "Beaver", "sku": "FB-217", "file": "flakes/beaver.webp"},
    {"name": "Blitz", "sku": "FB-241", "file": "flakes/blitz.webp"},
    {"name": "Boom", "sku": "FB-242", "file": "flakes/boom.webp"},
    {"name": "Bucky", "sku": "FB-223", "file": "flakes/bucky.webp"},
    {"name": "Charlotte", "sku": "FB-248", "file": "flakes/charlotte.webp"},
    {"name": "Conquer", "sku": "FB-246", "file": "flakes/conquer.webp"},
    {"name": "Flipper", "sku": "FB-236", "file": "flakes/flipper.webp"},
    {"name": "Ford", "sku": "FB-213", "file": "flakes/ford.webp"},
    {"name": "Freddie", "sku": "FB-256", "file": "flakes/freddie.webp"},
    {"name": "Gold Rush", "sku": "FB-253", "file": "flakes/gold-rush.webp"},
    {"name": "Green and Gold", "sku": "FB-982", "file": "flakes/green-and-gold.webp"},
    {"name": "Growl", "sku": "FB-255", "file": "flakes/growl.webp"},
    {"name": "Gumbo", "sku": "FB-238", "file": "flakes/gumbo.webp"},
    {"name": "Jax", "sku": "FB-234", "file": "flakes/jax.webp"},
    {"name": "LP Field", "sku": "FB-207", "file": "flakes/lp-field.webp"},
    {"name": "Lincoln", "sku": "FB-229", "file": "flakes/lincoln.webp"},
    {"name": "Milwaukee", "sku": "FB-231", "file": "flakes/milwaukee.webp"},
    {"name": "Pat", "sku": "FB-250", "file": "flakes/pat.webp"},
    {"name": "Poe", "sku": "FB-245", "file": "flakes/poe.webp"},
    {"name": "Rampage", "sku": "FB-235", "file": "flakes/rampage.webp"},
    {"name": "Rebel", "sku": "FB-251", "file": "flakes/rebel.webp"},
    {"name": "Rise", "sku": "FB-247", "file": "flakes/rise.webp"},
    {"name": "Roary", "sku": "FB-252", "file": "flakes/roary.webp"},
    {"name": "Rowdy", "sku": "FB-249", "file": "flakes/rowdy.webp"},
    {"name": "Skol", "sku": "FB-244", "file": "flakes/skol.webp"},
    {"name": "Splash", "sku": "FB-237", "file": "flakes/splash.webp"},
    {"name": "Steel City", "sku": "FB-240", "file": "flakes/steel-city.webp"},
    {"name": "Swoop", "sku": "FB-239", "file": "flakes/swoop.webp"},
    {"name": "Talon", "sku": "FB-257", "file": "flakes/talon.webp"},
    {"name": "The Land", "sku": "FB-233", "file": "flakes/the-land.webp"},
    {"name": "Tiger", "sku": "FB-254", "file": "flakes/tiger.webp"},
    {"name": "Viktor", "sku": "FB-243", "file": "torginol/insignia/viktor.webp"},
    {"name": "Whitewater", "sku": "FB-315", "file": "torginol/insignia/whitewater.webp"},
    {"name": "Windy City", "sku": "FB-232", "file": "flakes/windy-city.webp"},
  ] },
  { key: "mica-enhanced", title: "Mica-Enhanced", blurb: "Vinyl blends with natural mica for depth and sparkle.", items: [
    {"name": "Ammonite", "sku": "FB-5017", "file": "torginol/mica-enhanced/ammonite.webp"},
    {"name": "Bronzite", "sku": "FB-5009", "file": "torginol/mica-enhanced/bronzite.webp"},
    {"name": "Coastal", "sku": "FB-5022", "file": "torginol/mica-enhanced/coastal.webp"},
    {"name": "Confetti", "sku": "FB-5003", "file": "torginol/mica-enhanced/confetti.webp"},
    {"name": "Crescent Moon", "sku": "FB-5021", "file": "torginol/mica-enhanced/crescent-moon.webp"},
    {"name": "Cyprus", "sku": "FB-5010", "file": "torginol/mica-enhanced/cyprus.webp"},
    {"name": "Dusk", "sku": "FB-5020", "file": "torginol/mica-enhanced/dusk.webp"},
    {"name": "Fireball", "sku": "FB-5001", "file": "torginol/mica-enhanced/fireball.webp"},
    {"name": "Foundry", "sku": "FB-5304", "file": "torginol/mica-enhanced/foundry.webp"},
    {"name": "Gemstone", "sku": "FB-5016", "file": "torginol/mica-enhanced/gemstone.webp"},
    {"name": "Geode", "sku": "FB-5014", "file": "torginol/mica-enhanced/geode.webp"},
    {"name": "Gilded", "sku": "FB-5301", "file": "torginol/mica-enhanced/gilded.webp"},
    {"name": "Jazz", "sku": "FB-5002", "file": "torginol/mica-enhanced/jazz.webp"},
    {"name": "Lava Rock", "sku": "FB-5012", "file": "torginol/mica-enhanced/lava-rock.webp"},
    {"name": "Midnight Lagoon", "sku": "FB-5004", "file": "torginol/mica-enhanced/midnight-lagoon.webp"},
    {"name": "New Penny", "sku": "FB-5302", "file": "torginol/mica-enhanced/new-penny.webp"},
    {"name": "Onyx", "sku": "FB-5018", "file": "torginol/mica-enhanced/onyx.webp"},
    {"name": "Peppercorn", "sku": "FB-5008", "file": "torginol/mica-enhanced/peppercorn.webp"},
    {"name": "Pyrite", "sku": "FB-5015", "file": "torginol/mica-enhanced/pyrite.webp"},
    {"name": "Russet", "sku": "FB-5303", "file": "torginol/mica-enhanced/russet.webp"},
    {"name": "Sea Glass", "sku": "FB-5011", "file": "torginol/mica-enhanced/sea-glass.webp"},
    {"name": "Sea Salt", "sku": "FB-5005", "file": "torginol/mica-enhanced/sea-salt.webp"},
    {"name": "Smokestone", "sku": "FB-5007", "file": "torginol/mica-enhanced/smokestone.webp"},
    {"name": "Tidepool", "sku": "FB-5019", "file": "torginol/mica-enhanced/tidepool.webp"},
    {"name": "Treasure", "sku": "FB-5006", "file": "torginol/mica-enhanced/treasure.webp"},
    {"name": "Whitecap", "sku": "FB-5013", "file": "torginol/mica-enhanced/whitecap.webp"},
  ] },
  { key: "shimmer", title: "Shimmer & Glitter", blurb: "Reflective accents broadcast alone or over any blend.", items: [
    {"name": "Aurora Accent", "sku": "FB-3301", "file": "torginol/glitter/aurora-accent.webp"},
    {"name": "Black (Hex)", "sku": "", "file": "torginol/glitter-hex/black.webp"},
    {"name": "Black (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/black.webp"},
    {"name": "Blue (Hex)", "sku": "", "file": "torginol/glitter-hex/blue.webp"},
    {"name": "Bronze (Hex)", "sku": "", "file": "torginol/glitter-hex/bronze.webp"},
    {"name": "Bronze (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/bronze.webp"},
    {"name": "Brown (Hex)", "sku": "", "file": "torginol/glitter-hex/brown.webp"},
    {"name": "Brown (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/brown.webp"},
    {"name": "Copper (Hex)", "sku": "", "file": "torginol/glitter-hex/copper.webp"},
    {"name": "Copper (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/copper.webp"},
    {"name": "Creekbed Accent", "sku": "FB-715", "file": "torginol/glitter/creekbed-accent.webp"},
    {"name": "Crystallina (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/crystallina.webp"},
    {"name": "Dolerite Accent", "sku": "FB-9311", "file": "torginol/glitter/dolerite-accent.webp"},
    {"name": "Domino Accent", "sku": "FB-411", "file": "torginol/glitter/domino-accent.webp"},
    {"name": "Fuchsia (Hex)", "sku": "", "file": "torginol/glitter-hex/fuchsia.webp"},
    {"name": "Gold (Hex)", "sku": "", "file": "torginol/glitter-hex/gold.webp"},
    {"name": "Gold (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/gold.webp"},
    {"name": "Green (Hex)", "sku": "", "file": "torginol/glitter-hex/green.webp"},
    {"name": "Gunmetal (Hex)", "sku": "", "file": "torginol/glitter-hex/gunmetal.webp"},
    {"name": "Gunmetal (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/gunmetal.webp"},
    {"name": "Holographic (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/holographic.webp"},
    {"name": "Madras Accent", "sku": "FB-706", "file": "torginol/glitter/madras-accent.webp"},
    {"name": "Midnight (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/midnight.webp"},
    {"name": "Nordic Green Accent", "sku": "FB-514", "file": "torginol/glitter/nordic-green-accent.webp"},
    {"name": "Outback Accent", "sku": "FB-517", "file": "torginol/glitter/outback-accent.webp"},
    {"name": "Red (Hex)", "sku": "", "file": "torginol/glitter-hex/red.webp"},
    {"name": "Silver (Hex)", "sku": "", "file": "torginol/glitter-hex/silver.webp"},
    {"name": "Silver (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/silver.webp"},
    {"name": "Stargazer Accent", "sku": "FB-908", "file": "torginol/glitter/stargazer-accent.webp"},
    {"name": "Stonehenge Accent", "sku": "FB-427", "file": "torginol/glitter/stonehenge-accent.webp"},
    {"name": "Strudel Accent", "sku": "FB-502", "file": "torginol/glitter/strudel-accent.webp"},
    {"name": "Victorian Accent", "sku": "FB-818", "file": "torginol/glitter/victorian-accent.webp"},
    {"name": "White (Random Cut)", "sku": "", "file": "torginol/glitter-random-cut/white.webp"},
    {"name": "Yellow (Hex)", "sku": "", "file": "torginol/glitter-hex/yellow.webp"},
  ] },
  { key: "solid-colors", title: "Solid Colors", blurb: "Single-color flake \u2014 build your own custom blend ratio.", items: [
    {"name": "Acorn", "sku": "F5117", "file": "torginol/solid-colors/acorn.webp"},
    {"name": "Adobe Beige", "sku": "F1000", "file": "torginol/solid-colors/adobe-beige.webp"},
    {"name": "African Violet", "sku": "F5104", "file": "torginol/solid-colors/african-violet.webp"},
    {"name": "Aloha Rose", "sku": "F3130", "file": "torginol/solid-colors/aloha-rose.webp"},
    {"name": "Alpaca White", "sku": "F9958", "file": "torginol/solid-colors/alpaca-white.webp"},
    {"name": "Amethyst", "sku": "F1020", "file": "torginol/solid-colors/amethyst.webp"},
    {"name": "Antique White", "sku": "F9959", "file": "torginol/solid-colors/antique-white.webp"},
    {"name": "Aquamarine", "sku": "F9952", "file": "torginol/solid-colors/aquamarine.webp"},
    {"name": "Autumn Brown", "sku": "F1040", "file": "torginol/solid-colors/autumn-brown.webp"},
    {"name": "Baby Blue", "sku": "F9988", "file": "torginol/solid-colors/baby-blue.webp"},
    {"name": "Battleship Gray", "sku": "F9955", "file": "torginol/solid-colors/battleship-gray.webp"},
    {"name": "Beige", "sku": "F1045", "file": "torginol/solid-colors/beige.webp"},
    {"name": "Berry", "sku": "F9995", "file": "torginol/solid-colors/berry.webp"},
    {"name": "Black", "sku": "F1050", "file": "torginol/solid-colors/black.webp"},
    {"name": "Black Iron Oxide", "sku": "F9902", "file": "torginol/solid-colors/black-iron-oxide.webp"},
    {"name": "Blue Ox", "sku": "F9907", "file": "torginol/solid-colors/blue-ox.webp"},
    {"name": "Brown", "sku": "F1060", "file": "torginol/solid-colors/brown.webp"},
    {"name": "Buff", "sku": "F6601", "file": "torginol/solid-colors/buff.webp"},
    {"name": "Burgundy", "sku": "F1070", "file": "torginol/solid-colors/burgundy.webp"},
    {"name": "Burnt Red", "sku": "F6609", "file": "torginol/solid-colors/burnt-red.webp"},
    {"name": "Buttermilk", "sku": "F9910", "file": "torginol/solid-colors/buttermilk.webp"},
    {"name": "Camelback", "sku": "F5307", "file": "torginol/solid-colors/camelback.webp"},
    {"name": "Camo Green", "sku": "F6723", "file": "torginol/solid-colors/camo-green.webp"},
    {"name": "Canyon Red", "sku": "F1080", "file": "torginol/solid-colors/canyon-red.webp"},
    {"name": "Cappuccino", "sku": "F5303", "file": "torginol/solid-colors/cappuccino.webp"},
    {"name": "Caramel", "sku": "F9954", "file": "torginol/solid-colors/caramel.webp"},
    {"name": "Cardboard", "sku": "F5302", "file": "torginol/solid-colors/cardboard.webp"},
    {"name": "Carrot Cake", "sku": "F9805", "file": "torginol/solid-colors/carrot-cake.webp"},
    {"name": "Cement", "sku": "F5252", "file": "torginol/solid-colors/cement.webp"},
    {"name": "Charcoal", "sku": "F1090", "file": "torginol/solid-colors/charcoal.webp"},
    {"name": "Cherry Bomb", "sku": "F9920", "file": "torginol/solid-colors/cherry-bomb.webp"},
    {"name": "Chiffon", "sku": "F9806", "file": "torginol/solid-colors/chiffon.webp"},
    {"name": "Chocolate", "sku": "F5052", "file": "torginol/solid-colors/chocolate.webp"},
    {"name": "Clay", "sku": "F6607", "file": "torginol/solid-colors/clay.webp"},
    {"name": "Cobalt Blue", "sku": "F9963", "file": "torginol/solid-colors/cobalt-blue.webp"},
    {"name": "Cocoa Brown", "sku": "F1100", "file": "torginol/solid-colors/cocoa-brown.webp"},
    {"name": "Coppertone", "sku": "F9973", "file": "torginol/solid-colors/coppertone.webp"},
    {"name": "Cornmeal", "sku": "F5301", "file": "torginol/solid-colors/cornmeal.webp"},
    {"name": "Cosmo", "sku": "F9992", "file": "torginol/solid-colors/cosmo.webp"},
    {"name": "Cream", "sku": "F6614", "file": "torginol/solid-colors/cream.webp"},
    {"name": "Crest Green", "sku": "F1120", "file": "torginol/solid-colors/crest-green.webp"},
    {"name": "Cyberspace", "sku": "F5920", "file": "torginol/solid-colors/cyberspace.webp"},
    {"name": "Dark Blue", "sku": "F1130", "file": "torginol/solid-colors/dark-blue.webp"},
    {"name": "Dark Brown", "sku": "F5501", "file": "torginol/solid-colors/dark-brown.webp"},
    {"name": "Dark Gray", "sku": "F9904", "file": "torginol/solid-colors/dark-gray.webp"},
    {"name": "Delray Blue", "sku": "F1140", "file": "torginol/solid-colors/delray-blue.webp"},
    {"name": "Dolphin", "sku": "F9801", "file": "torginol/solid-colors/dolphin.webp"},
    {"name": "Dove Gray", "sku": "F1160", "file": "torginol/solid-colors/dove-gray.webp"},
    {"name": "Dusk Blue", "sku": "F1200", "file": "torginol/solid-colors/dusk-blue.webp"},
    {"name": "Ebony", "sku": "F5114", "file": "torginol/solid-colors/ebony.webp"},
    {"name": "Eggshell", "sku": "F9986", "file": "torginol/solid-colors/eggshell.webp"},
    {"name": "Ewa Green", "sku": "F3020", "file": "torginol/solid-colors/ewa-green.webp"},
    {"name": "Favre", "sku": "F9916", "file": "torginol/solid-colors/favre.webp"},
    {"name": "Fawn", "sku": "F1320", "file": "torginol/solid-colors/fawn.webp"},
    {"name": "Fireweed", "sku": "F5118", "file": "torginol/solid-colors/fireweed.webp"},
    {"name": "Forest Green", "sku": "F1360", "file": "torginol/solid-colors/forest-green.webp"},
    {"name": "Fossil", "sku": "F9911", "file": "torginol/solid-colors/fossil.webp"},
    {"name": "Functional Gray", "sku": "F9961", "file": "torginol/solid-colors/functional-gray.webp"},
    {"name": "Gardenview", "sku": "F9991", "file": "torginol/solid-colors/gardenview.webp"},
    {"name": "Gladiola", "sku": "F6804", "file": "torginol/solid-colors/gladiola.webp"},
    {"name": "Gold", "sku": "F1400", "file": "torginol/solid-colors/gold.webp"},
    {"name": "Granite", "sku": "F1410", "file": "torginol/solid-colors/granite.webp"},
    {"name": "Grape", "sku": "F9993", "file": "torginol/solid-colors/grape.webp"},
    {"name": "Graphite", "sku": "F1415", "file": "torginol/solid-colors/graphite.webp"},
    {"name": "Gravy", "sku": "F9982", "file": "torginol/solid-colors/gravy.webp"},
    {"name": "Grounded", "sku": "F2518", "file": "torginol/solid-colors/grounded.webp"},
    {"name": "Heaven", "sku": "F9905", "file": "torginol/solid-colors/heaven.webp"},
    {"name": "Hunter Green", "sku": "F1420", "file": "torginol/solid-colors/hunter-green.webp"},
    {"name": "Hypnotic", "sku": "F9983", "file": "torginol/solid-colors/hypnotic.webp"},
    {"name": "Ivory", "sku": "F1425", "file": "torginol/solid-colors/ivory.webp"},
    {"name": "JD Green", "sku": "F5910", "file": "torginol/solid-colors/jd-green.webp"},
    {"name": "Jasper", "sku": "F1430", "file": "torginol/solid-colors/jasper.webp"},
    {"name": "Jetstream", "sku": "F9962", "file": "torginol/solid-colors/jetstream.webp"},
    {"name": "Khaki", "sku": "F9956", "file": "torginol/solid-colors/khaki.webp"},
    {"name": "Kona Beige", "sku": "F3040", "file": "torginol/solid-colors/kona-beige.webp"},
    {"name": "Latte", "sku": "F6602", "file": "torginol/solid-colors/latte.webp"},
    {"name": "Lavender", "sku": "F9965", "file": "torginol/solid-colors/lavender.webp"},
    {"name": "Lime", "sku": "F5102", "file": "torginol/solid-colors/lime.webp"},
    {"name": "Lipstick Red", "sku": "F6721", "file": "torginol/solid-colors/lipstick-red.webp"},
    {"name": "Maui Blue", "sku": "F3100", "file": "torginol/solid-colors/maui-blue.webp"},
    {"name": "Medium Gray", "sku": "F1480", "file": "torginol/solid-colors/medium-gray.webp"},
    {"name": "Milkweed", "sku": "F1520", "file": "torginol/solid-colors/milkweed.webp"},
    {"name": "Mint Green", "sku": "F1560", "file": "torginol/solid-colors/mint-green.webp"},
    {"name": "Moody Blue", "sku": "F9972", "file": "torginol/solid-colors/moody-blue.webp"},
    {"name": "Moonshine", "sku": "F5201", "file": "torginol/solid-colors/moonshine.webp"},
    {"name": "Morning Fog", "sku": "F9966", "file": "torginol/solid-colors/morning-fog.webp"},
    {"name": "Moss", "sku": "F9970", "file": "torginol/solid-colors/moss.webp"},
    {"name": "Mud", "sku": "F5304", "file": "torginol/solid-colors/mud.webp"},
    {"name": "Mustard", "sku": "F1570", "file": "torginol/solid-colors/mustard.webp"},
    {"name": "Navajo Beige", "sku": "F9960", "file": "torginol/solid-colors/navajo-beige.webp"},
    {"name": "Navy", "sku": "F9969", "file": "torginol/solid-colors/navy.webp"},
    {"name": "Neutral Gray", "sku": "F6606", "file": "torginol/solid-colors/neutral-gray.webp"},
    {"name": "Oahu Brown", "sku": "F3000", "file": "torginol/solid-colors/oahu-brown.webp"},
    {"name": "Olive", "sku": "F1600", "file": "torginol/solid-colors/olive.webp"},
    {"name": "Online", "sku": "F9903", "file": "torginol/solid-colors/online.webp"},
    {"name": "Orange", "sku": "F2160", "file": "torginol/solid-colors/orange.webp"},
    {"name": "Pali Brown", "sku": "F3120", "file": "torginol/solid-colors/pali-brown.webp"},
    {"name": "Patio Red", "sku": "F1640", "file": "torginol/solid-colors/patio-red.webp"},
    {"name": "Peach", "sku": "F1680", "file": "torginol/solid-colors/peach.webp"},
    {"name": "Peppermint", "sku": "F9971", "file": "torginol/solid-colors/peppermint.webp"},
    {"name": "Plum", "sku": "F9951", "file": "torginol/solid-colors/plum.webp"},
    {"name": "Porpoise", "sku": "F5306", "file": "torginol/solid-colors/porpoise.webp"},
    {"name": "Potter", "sku": "F9981", "file": "torginol/solid-colors/potter.webp"},
    {"name": "Powder Blue", "sku": "F1720", "file": "torginol/solid-colors/powder-blue.webp"},
    {"name": "Primary Blue", "sku": "F6604", "file": "torginol/solid-colors/primary-blue.webp"},
    {"name": "Primary Yellow", "sku": "F2200", "file": "torginol/solid-colors/primary-yellow.webp"},
    {"name": "Purple Gray", "sku": "F2510", "file": "torginol/solid-colors/purple-gray.webp"},
    {"name": "Purple Haze", "sku": "F9989", "file": "torginol/solid-colors/purple-haze.webp"},
    {"name": "Putty", "sku": "F5115", "file": "torginol/solid-colors/putty.webp"},
    {"name": "Raisin", "sku": "F9975", "file": "torginol/solid-colors/raisin.webp"},
    {"name": "Red", "sku": "F2240", "file": "torginol/solid-colors/red.webp"},
    {"name": "Redwood", "sku": "F9996", "file": "torginol/solid-colors/redwood.webp"},
    {"name": "Rhino Gray", "sku": "F2563", "file": "torginol/solid-colors/rhino-gray.webp"},
    {"name": "Rose", "sku": "F1760", "file": "torginol/solid-colors/rose.webp"},
    {"name": "Royal Blue", "sku": "F9967", "file": "torginol/solid-colors/royal-blue.webp"},
    {"name": "Rustic Red", "sku": "F5935", "file": "torginol/solid-colors/rustic-red.webp"},
    {"name": "Sage", "sku": "F6613", "file": "torginol/solid-colors/sage.webp"},
    {"name": "Salmon", "sku": "F1770", "file": "torginol/solid-colors/salmon.webp"},
    {"name": "Sand Dune", "sku": "F9994", "file": "torginol/solid-colors/sand-dune.webp"},
    {"name": "Scone", "sku": "F1780", "file": "torginol/solid-colors/scone.webp"},
    {"name": "Seaspray", "sku": "F5101", "file": "torginol/solid-colors/seaspray.webp"},
    {"name": "Semi-Transparent White", "sku": "F2250", "file": "torginol/solid-colors/semi-transparent-white.webp"},
    {"name": "Sky Blue", "sku": "F9964", "file": "torginol/solid-colors/sky-blue.webp"},
    {"name": "Slime", "sku": "F9990", "file": "torginol/solid-colors/slime.webp"},
    {"name": "Sommelier", "sku": "F9800", "file": "torginol/solid-colors/sommelier.webp"},
    {"name": "Sonic", "sku": "F9984", "file": "torginol/solid-colors/sonic.webp"},
    {"name": "Sorbet", "sku": "F5103", "file": "torginol/solid-colors/sorbet.webp"},
    {"name": "Space Gray", "sku": "F5182", "file": "torginol/solid-colors/space-gray.webp"},
    {"name": "Squash", "sku": "F9979", "file": "torginol/solid-colors/squash.webp"},
    {"name": "Steel Blue", "sku": "F9968", "file": "torginol/solid-colors/steel-blue.webp"},
    {"name": "Sticks &amp; Stones", "sku": "F5219", "file": "torginol/solid-colors/sticks-amp-stones.webp"},
    {"name": "Stone", "sku": "F9987", "file": "torginol/solid-colors/stone.webp"},
    {"name": "Stormy Blue", "sku": "F6621", "file": "torginol/solid-colors/stormy-blue.webp"},
    {"name": "Sugar Cookie", "sku": "F9909", "file": "torginol/solid-colors/sugar-cookie.webp"},
    {"name": "Sunrise Yellow", "sku": "F6622", "file": "torginol/solid-colors/sunrise-yellow.webp"},
    {"name": "Tabu", "sku": "F5305", "file": "torginol/solid-colors/tabu.webp"},
    {"name": "Tan", "sku": "F1785", "file": "torginol/solid-colors/tan.webp"},
    {"name": "Taupe", "sku": "F9957", "file": "torginol/solid-colors/taupe.webp"},
    {"name": "Teal", "sku": "F6617", "file": "torginol/solid-colors/teal.webp"},
    {"name": "Terra Cotta", "sku": "F7551", "file": "torginol/solid-colors/terra-cotta.webp"},
    {"name": "Toast", "sku": "F9912", "file": "torginol/solid-colors/toast.webp"},
    {"name": "Tomato", "sku": "F9978", "file": "torginol/solid-colors/tomato.webp"},
    {"name": "True Blue", "sku": "F1790", "file": "torginol/solid-colors/true-blue.webp"},
    {"name": "Whisper Gray", "sku": "F1800", "file": "torginol/solid-colors/whisper-gray.webp"},
    {"name": "White", "sku": "F1820", "file": "torginol/solid-colors/white.webp"},
    {"name": "Wigwam", "sku": "F5116", "file": "torginol/solid-colors/wigwam.webp"},
  ] },
  { key: "archive", title: "Classic Archive", blurb: "Long-running classics from the Torginol archive, available special-order.", items: [
    {"name": "Almond", "sku": "FB-605", "file": "torginol/archive/almond.webp"},
    {"name": "Alpine", "sku": "FB-103", "file": "torginol/archive/alpine.webp"},
    {"name": "Appalachian", "sku": "FB-812", "file": "torginol/archive/appalachian.webp"},
    {"name": "Arctic", "sku": "FB-704", "file": "flakes/arctic.webp"},
    {"name": "Argyle", "sku": "FB-303", "file": "torginol/archive/argyle.webp"},
    {"name": "Baboon", "sku": "FB-964", "file": "torginol/archive/baboon.webp"},
    {"name": "Bandit", "sku": "FB-126", "file": "torginol/archive/bandit.webp"},
    {"name": "Barn Owl", "sku": "FB-1004", "file": "torginol/archive/barn-owl.webp"},
    {"name": "Barrel", "sku": "FB-110", "file": "torginol/archive/barrel.webp"},
    {"name": "Basil", "sku": "FB-418", "file": "torginol/archive/basil.webp"},
    {"name": "Basset", "sku": "FB-105", "file": "torginol/archive/basset.webp"},
    {"name": "Beachcomber", "sku": "FB-603", "file": "torginol/archive/beachcomber.webp"},
    {"name": "Beast", "sku": "FB-955", "file": "torginol/archive/beast.webp"},
    {"name": "Belle", "sku": "FB-124", "file": "torginol/archive/belle.webp"},
    {"name": "Birch Bark", "sku": "FB-1005", "file": "flakes/birch-bark.webp"},
    {"name": "Birthday Cake", "sku": "FB-816", "file": "torginol/archive/birthday-cake.webp"},
    {"name": "Blue Heron", "sku": "FB-1006", "file": "torginol/archive/blue-heron.webp"},
    {"name": "Blue Lagoon", "sku": "FB-819", "file": "torginol/archive/blue-lagoon.webp"},
    {"name": "Blue Wing", "sku": "FB-116", "file": "torginol/archive/blue-wing.webp"},
    {"name": "Briar", "sku": "FB-221", "file": "flakes/briar.webp"},
    {"name": "Brookside", "sku": "FB-117", "file": "torginol/archive/brookside.webp"},
    {"name": "Brown Sugar", "sku": "FB-961", "file": "torginol/archive/brown-sugar.webp"},
    {"name": "Buckskin", "sku": "FB-614", "file": "torginol/archive/buckskin.webp"},
    {"name": "Burlap", "sku": "FB-417", "file": "torginol/archive/burlap.webp"},
    {"name": "Burlwood", "sku": "FB-305", "file": "torginol/archive/burlwood.webp"},
    {"name": "Cam", "sku": "FB-206", "file": "flakes/cam.webp"},
    {"name": "Camel", "sku": "FB-413", "file": "torginol/archive/camel.webp"},
    {"name": "Cannoli", "sku": "FB-130", "file": "flakes/cannoli.webp"},
    {"name": "Cardinal", "sku": "FB-230", "file": "flakes/cardinal.webp"},
    {"name": "Carey", "sku": "FB-227", "file": "flakes/carey.webp"},
    {"name": "Caribou", "sku": "FB-104", "file": "torginol/archive/caribou.webp"},
    {"name": "Cashmere", "sku": "FB-129", "file": "torginol/archive/cashmere.webp"},
    {"name": "Cato", "sku": "FB-121", "file": "torginol/archive/cato.webp"},
    {"name": "Cedar", "sku": "FB-815", "file": "torginol/archive/cedar.webp"},
    {"name": "Chameleon", "sku": "FB-309", "file": "torginol/archive/chameleon.webp"},
    {"name": "Chestnut", "sku": "FB-822", "file": "torginol/archive/chestnut.webp"},
    {"name": "Cleveland Chomps", "sku": "FB-205", "file": "torginol/archive/cleveland-chomps.webp"},
    {"name": "Clover", "sku": "FB-808", "file": "torginol/archive/clover.webp"},
    {"name": "Cobblestone", "sku": "FB-422", "file": "torginol/archive/cobblestone.webp"},
    {"name": "Coliseum", "sku": "FB-216", "file": "flakes/coliseum.webp"},
    {"name": "Colonial", "sku": "FB-817", "file": "flakes/colonial.webp"},
    {"name": "Crimson", "sku": "FB-123", "file": "torginol/archive/crimson.webp"},
    {"name": "Cruller", "sku": "FB-820", "file": "torginol/archive/cruller.webp"},
    {"name": "Dahlia", "sku": "FB-308", "file": "torginol/archive/dahlia.webp"},
    {"name": "Dakota Trail", "sku": "FB-607", "file": "torginol/archive/dakota-trail.webp"},
    {"name": "Danish", "sku": "FB-118", "file": "torginol/archive/danish.webp"},
    {"name": "Daredevil", "sku": "FB-220", "file": "flakes/daredevil.webp"},
    {"name": "Doak", "sku": "FB-212", "file": "flakes/doak.webp"},
    {"name": "Dory", "sku": "FB-307", "file": "torginol/archive/dory.webp"},
    {"name": "Everbank", "sku": "FB-226", "file": "flakes/everbank.webp"},
    {"name": "Fern", "sku": "FB-102", "file": "torginol/archive/fern.webp"},
    {"name": "Finch", "sku": "FB-106", "file": "torginol/archive/finch.webp"},
    {"name": "Fireside", "sku": "FB-604", "file": "torginol/archive/fireside.webp"},
    {"name": "Fox", "sku": "FB-120", "file": "torginol/archive/fox.webp"},
    {"name": "Fritter", "sku": "FB-101", "file": "torginol/archive/fritter.webp"},
    {"name": "Gale", "sku": "FB-301", "file": "torginol/archive/gale.webp"},
    {"name": "Gargoyle", "sku": "FB-914", "file": "flakes/gargoyle.webp"},
    {"name": "Grasshopper", "sku": "FB-813", "file": "torginol/archive/grasshopper.webp"},
    {"name": "Green Bay", "sku": "FB-426", "file": "torginol/archive/green-bay.webp"},
    {"name": "Grizzly", "sku": "FB-965", "file": "torginol/archive/grizzly.webp"},
    {"name": "Harvest", "sku": "FB-412", "file": "torginol/archive/harvest.webp"},
    {"name": "Heinz", "sku": "FB-209", "file": "flakes/heinz.webp"},
    {"name": "Hillside", "sku": "FB-701", "file": "torginol/archive/hillside.webp"},
    {"name": "Himalayan", "sku": "FB-705", "file": "torginol/archive/himalayan.webp"},
    {"name": "Honeycomb", "sku": "FB-957", "file": "torginol/archive/honeycomb.webp"},
    {"name": "Huckleberry", "sku": "FB-311", "file": "torginol/archive/huckleberry.webp"},
    {"name": "Humphrey", "sku": "FB-225", "file": "flakes/humphrey.webp"},
    {"name": "Ice Blue", "sku": "FB-425", "file": "torginol/archive/ice-blue.webp"},
    {"name": "Iceberg", "sku": "FB-702", "file": "torginol/archive/iceberg.webp"},
    {"name": "Imperial", "sku": "FB-329", "file": "torginol/archive/imperial.webp"},
    {"name": "Iris", "sku": "FB-316", "file": "torginol/archive/iris.webp"},
    {"name": "Kalahari", "sku": "FB-519", "file": "torginol/archive/kalahari.webp"},
    {"name": "Kennedy", "sku": "FB-115", "file": "torginol/archive/kennedy.webp"},
    {"name": "Khaki", "sku": "FB-428", "file": "torginol/archive/khaki.webp"},
    {"name": "Kringle", "sku": "FB-515", "file": "torginol/archive/kringle.webp"},
    {"name": "Lambeau", "sku": "FB-201", "file": "flakes/lambeau.webp"},
    {"name": "Leopard", "sku": "FB-518", "file": "torginol/archive/leopard.webp"},
    {"name": "Lighthouse", "sku": "FB-302", "file": "torginol/archive/lighthouse.webp"},
    {"name": "Linden", "sku": "FB-963", "file": "torginol/archive/linden.webp"},
    {"name": "Lucas", "sku": "FB-218", "file": "flakes/lucas.webp"},
    {"name": "Lunar", "sku": "FB-904", "file": "flakes/lunar.webp"},
    {"name": "Madden", "sku": "FB-214", "file": "flakes/madden.webp"},
    {"name": "Maple Grove", "sku": "FB-323", "file": "torginol/archive/maple-grove.webp"},
    {"name": "Mardi Gras", "sku": "FB-317", "file": "torginol/archive/mardi-gras.webp"},
    {"name": "Matador", "sku": "FB-505", "file": "torginol/archive/matador.webp"},
    {"name": "Merlot", "sku": "FB-416", "file": "torginol/archive/merlot.webp"},
    {"name": "Metrodome", "sku": "FB-215", "file": "flakes/metrodome.webp"},
    {"name": "Midnight", "sku": "FB-423", "file": "torginol/archive/midnight.webp"},
    {"name": "Miller", "sku": "FB-208", "file": "flakes/miller.webp"},
    {"name": "Mink", "sku": "FB-109", "file": "torginol/archive/mink.webp"},
    {"name": "Mojito", "sku": "FB-958", "file": "torginol/archive/mojito.webp"},
    {"name": "Monroe", "sku": "FB-107", "file": "torginol/archive/monroe.webp"},
    {"name": "Montana", "sku": "FB-224", "file": "flakes/montana.webp"},
    {"name": "Monterrey", "sku": "FB-809", "file": "torginol/archive/monterrey.webp"},
    {"name": "Morning Dew", "sku": "FB-609", "file": "flakes/morning-dew.webp"},
    {"name": "Morocco", "sku": "FB-810", "file": "torginol/archive/morocco.webp"},
    {"name": "Moth", "sku": "FB-1001", "file": "torginol/archive/moth.webp"},
    {"name": "Mountain Green", "sku": "FB-322", "file": "torginol/archive/mountain-green.webp"},
    {"name": "Mudslide", "sku": "FB-108", "file": "torginol/archive/mudslide.webp"},
    {"name": "Oasis", "sku": "FB-712", "file": "flakes/oasis.webp"},
    {"name": "Olivine", "sku": "FB-710", "file": "torginol/archive/olivine.webp"},
    {"name": "Oregano", "sku": "FB-111", "file": "torginol/archive/oregano.webp"},
    {"name": "Palomino", "sku": "FB-804", "file": "torginol/archive/palomino.webp"},
    {"name": "Papillion", "sku": "FB-119", "file": "torginol/archive/papillion.webp"},
    {"name": "Paul Brown", "sku": "FB-204", "file": "flakes/paul-brown.webp"},
    {"name": "Pecan", "sku": "FB-125", "file": "torginol/archive/pecan.webp"},
    {"name": "Pembrook", "sku": "FB-114", "file": "torginol/archive/pembrook.webp"},
    {"name": "Persian", "sku": "FB-952", "file": "torginol/archive/persian.webp"},
    {"name": "Pheasant", "sku": "FB-318", "file": "torginol/archive/pheasant.webp"},
    {"name": "Pintail", "sku": "FB-324", "file": "torginol/archive/pintail.webp"},
    {"name": "Portico", "sku": "FB-707", "file": "torginol/archive/portico.webp"},
    {"name": "Portobello", "sku": "FB-512", "file": "torginol/archive/portobello.webp"},
    {"name": "Prairie", "sku": "FB-509", "file": "torginol/archive/prairie.webp"},
    {"name": "Primrose", "sku": "FB-128", "file": "torginol/archive/primrose.webp"},
    {"name": "Ram", "sku": "FB-210", "file": "flakes/ram.webp"},
    {"name": "Rapids", "sku": "FB-506", "file": "flakes/rapids.webp"},
    {"name": "Reliant", "sku": "FB-222", "file": "flakes/reliant.webp"},
    {"name": "Rescue Ranger", "sku": "FB-122", "file": "torginol/archive/rescue-ranger.webp"},
    {"name": "River Rock", "sku": "FB-1002", "file": "torginol/archive/river-rock.webp"},
    {"name": "Sand Dollar", "sku": "FB-951", "file": "flakes/sand-dollar.webp"},
    {"name": "Savannah", "sku": "FB-814", "file": "torginol/archive/savannah.webp"},
    {"name": "Scarecrow", "sku": "FB-615", "file": "torginol/archive/scarecrow.webp"},
    {"name": "Sea Crest", "sku": "FB-803", "file": "flakes/sea-crest.webp"},
    {"name": "Sea Mist", "sku": "FB-802", "file": "flakes/sea-mist.webp"},
    {"name": "Seaport", "sku": "FB-709", "file": "torginol/archive/seaport.webp"},
    {"name": "Setter", "sku": "FB-953", "file": "torginol/archive/setter.webp"},
    {"name": "Siberian", "sku": "FB-902", "file": "flakes/siberian.webp"},
    {"name": "Sierra", "sku": "FB-321", "file": "torginol/archive/sierra.webp"},
    {"name": "Smokehouse", "sku": "FB-306", "file": "torginol/archive/smokehouse.webp"},
    {"name": "Soldier", "sku": "FB-202", "file": "flakes/soldier.webp"},
    {"name": "Space Odyssey", "sku": "FB-312", "file": "torginol/archive/space-odyssey.webp"},
    {"name": "Spangle", "sku": "FB-219", "file": "flakes/spangle.webp"},
    {"name": "Spice", "sku": "FB-610", "file": "torginol/archive/spice.webp"},
    {"name": "Stinger", "sku": "FB-508", "file": "flakes/stinger.webp"},
    {"name": "Strudel", "sku": "FB-502", "file": "torginol/archive/strudel.webp"},
    {"name": "Submarine", "sku": "FB-608", "file": "flakes/submarine.webp"},
    {"name": "Sun Life", "sku": "FB-203", "file": "flakes/sun-life.webp"},
    {"name": "Sunset Beige", "sku": "FB-112", "file": "torginol/archive/sunset-beige.webp"},
    {"name": "Superdome", "sku": "FB-211", "file": "flakes/superdome.webp"},
    {"name": "Terrier", "sku": "FB-325", "file": "torginol/archive/terrier.webp"},
    {"name": "Thistle", "sku": "FB-510", "file": "torginol/archive/thistle.webp"},
    {"name": "Twine", "sku": "FB-956", "file": "torginol/archive/twine.webp"},
    {"name": "Victorian", "sku": "FB-818", "file": "flakes/victorian.webp"},
    {"name": "Washington", "sku": "FB-228", "file": "flakes/washington.webp"},
    {"name": "Welsch", "sku": "FB-805", "file": "torginol/archive/welsch.webp"},
    {"name": "Willow", "sku": "FB-511", "file": "torginol/archive/willow.webp"},
    {"name": "Winter Wren", "sku": "FB-1003", "file": "torginol/archive/winter-wren.webp"},
    {"name": "Yorkshire", "sku": "FB-501", "file": "torginol/archive/yorkshire.webp"},
    {"name": "\u00c9clair", "sku": "FB-326", "file": "torginol/archive/eclair.webp"},
  ] },
];

export default COLLECTIONS;
